package dynamodb

// DynamoDB's model-derived input validation: the constraint tables, walked by
// internal/modelcheck. Generated from AWS's own service model with
// `dzaudit cases dynamodb` rather than transcribed, and replayed case by case
// in dynamodb/rejection_parity_test.go.

import (
	"regexp"

	"github.com/doze-dev/doze-aws/internal/awshttp"
	"github.com/doze-dev/doze-aws/internal/modelcheck"
)

// validate refuses what the model says DynamoDB refuses.
func validate(body []byte, table []modelcheck.Constraint) *awshttp.APIError {
	return modelcheck.Validate(body, table)
}

// Constraint tables, one per operation, generated from AWS's own service
// model with `dzaudit cases dynamodb` rather than transcribed by hand.
//
// An operation missing from this map either states no constraints on its
// inputs or is one doze-aws does not dispatch — the latter refuses every
// request including a valid one, so it cannot be audited by replaying
// cases at all, and docs/api-support/dynamodb.md records which.
var constraintTables = map[string][]modelcheck.Constraint{
	"BatchExecuteStatement": {
		{Path: "ReturnConsumedCapacity", Kind: modelcheck.KindEnum, Enum: []string{"INDEXES", "TOTAL", "NONE"}},
		{Path: "Statements", Kind: modelcheck.KindRequired},
		{Path: "Statements[].ReturnValuesOnConditionCheckFailure", Kind: modelcheck.KindEnum, Enum: []string{"ALL_OLD", "NONE"}},
		{Path: "Statements[].Statement", Kind: modelcheck.KindLength, Min: 1, Max: 8192},
		{Path: "Statements[].Statement", Kind: modelcheck.KindRequired},
	},
	"BatchGetItem": {
		{Path: "RequestItems", Kind: modelcheck.KindRequired},
		{Path: "RequestItems{}.AttributesToGet[]", Kind: modelcheck.KindLength, Min: 0, Max: 65535},
		{Path: "RequestItems{}.ExpressionAttributeNames{}", Kind: modelcheck.KindLength, Min: 0, Max: 65535},
		{Path: "RequestItems{}.Keys", Kind: modelcheck.KindRequired},
		{Path: "ReturnConsumedCapacity", Kind: modelcheck.KindEnum, Enum: []string{"TOTAL", "NONE", "INDEXES"}},
	},
	"BatchWriteItem": {
		{Path: "RequestItems", Kind: modelcheck.KindRequired},
		{Path: "RequestItems{}[].DeleteRequest.Key", Kind: modelcheck.KindRequired},
		{Path: "RequestItems{}[].PutRequest.Item", Kind: modelcheck.KindRequired},
		{Path: "ReturnConsumedCapacity", Kind: modelcheck.KindEnum, Enum: []string{"NONE", "INDEXES", "TOTAL"}},
		{Path: "ReturnItemCollectionMetrics", Kind: modelcheck.KindEnum, Enum: []string{"SIZE", "NONE"}},
	},
	"CreateTable": {
		{Path: "AttributeDefinitions[].AttributeName", Kind: modelcheck.KindLength, Min: 1, Max: 255},
		{Path: "AttributeDefinitions[].AttributeName", Kind: modelcheck.KindRequired},
		{Path: "AttributeDefinitions[].AttributeType", Kind: modelcheck.KindEnum, Enum: []string{"B", "S", "N"}},
		{Path: "AttributeDefinitions[].AttributeType", Kind: modelcheck.KindRequired},
		{Path: "BillingMode", Kind: modelcheck.KindEnum, Enum: []string{"PROVISIONED", "PAY_PER_REQUEST"}},
		{Path: "GlobalSecondaryIndexes[].IndexName", Kind: modelcheck.KindLength, Min: 3, Max: 255},
		{Path: "GlobalSecondaryIndexes[].IndexName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "GlobalSecondaryIndexes[].IndexName", Kind: modelcheck.KindRequired},
		{Path: "GlobalSecondaryIndexes[].KeySchema", Kind: modelcheck.KindRequired},
		{Path: "GlobalSecondaryIndexes[].KeySchema[].AttributeName", Kind: modelcheck.KindRequired},
		{Path: "GlobalSecondaryIndexes[].KeySchema[].KeyType", Kind: modelcheck.KindRequired},
		{Path: "GlobalSecondaryIndexes[].Projection", Kind: modelcheck.KindRequired},
		{Path: "GlobalSecondaryIndexes[].Projection.ProjectionType", Kind: modelcheck.KindEnum, Enum: []string{"ALL", "KEYS_ONLY", "INCLUDE"}},
		{Path: "GlobalSecondaryIndexes[].ProvisionedThroughput.ReadCapacityUnits", Kind: modelcheck.KindRange, Min: 1, Max: modelcheck.NoMax},
		{Path: "GlobalSecondaryIndexes[].ProvisionedThroughput.ReadCapacityUnits", Kind: modelcheck.KindRequired},
		{Path: "GlobalSecondaryIndexes[].ProvisionedThroughput.WriteCapacityUnits", Kind: modelcheck.KindRange, Min: 1, Max: modelcheck.NoMax},
		{Path: "GlobalSecondaryIndexes[].ProvisionedThroughput.WriteCapacityUnits", Kind: modelcheck.KindRequired},
		{Path: "GlobalTableSettingsReplicationMode", Kind: modelcheck.KindEnum, Enum: []string{"ENABLED", "DISABLED", "ENABLED_WITH_OVERRIDES"}},
		{Path: "GlobalTableSourceArn", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "KeySchema[].AttributeName", Kind: modelcheck.KindLength, Min: 1, Max: 255},
		{Path: "KeySchema[].AttributeName", Kind: modelcheck.KindRequired},
		{Path: "KeySchema[].KeyType", Kind: modelcheck.KindEnum, Enum: []string{"RANGE", "HASH"}},
		{Path: "KeySchema[].KeyType", Kind: modelcheck.KindRequired},
		{Path: "LocalSecondaryIndexes[].IndexName", Kind: modelcheck.KindLength, Min: 3, Max: 255},
		{Path: "LocalSecondaryIndexes[].IndexName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "LocalSecondaryIndexes[].IndexName", Kind: modelcheck.KindRequired},
		{Path: "LocalSecondaryIndexes[].KeySchema", Kind: modelcheck.KindRequired},
		{Path: "LocalSecondaryIndexes[].KeySchema[].AttributeName", Kind: modelcheck.KindRequired},
		{Path: "LocalSecondaryIndexes[].KeySchema[].KeyType", Kind: modelcheck.KindRequired},
		{Path: "LocalSecondaryIndexes[].Projection", Kind: modelcheck.KindRequired},
		{Path: "LocalSecondaryIndexes[].Projection.ProjectionType", Kind: modelcheck.KindEnum, Enum: []string{"KEYS_ONLY", "INCLUDE", "ALL"}},
		{Path: "ProvisionedThroughput.ReadCapacityUnits", Kind: modelcheck.KindRange, Min: 1, Max: modelcheck.NoMax},
		{Path: "ProvisionedThroughput.ReadCapacityUnits", Kind: modelcheck.KindRequired},
		{Path: "ProvisionedThroughput.WriteCapacityUnits", Kind: modelcheck.KindRange, Min: 1, Max: modelcheck.NoMax},
		{Path: "ProvisionedThroughput.WriteCapacityUnits", Kind: modelcheck.KindRequired},
		{Path: "SSESpecification.SSEType", Kind: modelcheck.KindEnum, Enum: []string{"AES256", "KMS"}},
		{Path: "StreamSpecification.StreamEnabled", Kind: modelcheck.KindRequired},
		{Path: "StreamSpecification.StreamViewType", Kind: modelcheck.KindEnum, Enum: []string{"NEW_IMAGE", "OLD_IMAGE", "NEW_AND_OLD_IMAGES", "KEYS_ONLY"}},
		{Path: "TableClass", Kind: modelcheck.KindEnum, Enum: []string{"STANDARD_INFREQUENT_ACCESS", "STANDARD"}},
		{Path: "TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TableName", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Key", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Tags[].Key", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Value", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Tags[].Value", Kind: modelcheck.KindRequired},
		{Path: "VectorIndexes[].Dimensions", Kind: modelcheck.KindRange, Min: 1, Max: modelcheck.NoMax},
		{Path: "VectorIndexes[].Dimensions", Kind: modelcheck.KindRequired},
		{Path: "VectorIndexes[].DistanceFunction", Kind: modelcheck.KindEnum, Enum: []string{"EUCLIDEAN", "COSINE", "DOT_PRODUCT"}},
		{Path: "VectorIndexes[].DistanceFunction", Kind: modelcheck.KindRequired},
		{Path: "VectorIndexes[].IndexName", Kind: modelcheck.KindLength, Min: 3, Max: 255},
		{Path: "VectorIndexes[].IndexName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "VectorIndexes[].IndexName", Kind: modelcheck.KindRequired},
		{Path: "VectorIndexes[].Projection", Kind: modelcheck.KindRequired},
		{Path: "VectorIndexes[].Projection.ProjectionType", Kind: modelcheck.KindEnum, Enum: []string{"KEYS_ONLY", "INCLUDE", "ALL"}},
		{Path: "VectorIndexes[].SearchSchema[].AttributeName", Kind: modelcheck.KindRequired},
		{Path: "VectorIndexes[].SearchSchema[].SearchSchemaElementType", Kind: modelcheck.KindRequired},
		{Path: "VectorIndexes[].VectorAttribute", Kind: modelcheck.KindRequired},
		{Path: "VectorIndexes[].VectorAttribute.AttributeName", Kind: modelcheck.KindLength, Min: 1, Max: 255},
		{Path: "VectorIndexes[].VectorAttribute.AttributeName", Kind: modelcheck.KindRequired},
	},
	"DeleteItem": {
		{Path: "ConditionalOperator", Kind: modelcheck.KindEnum, Enum: []string{"AND", "OR"}},
		{Path: "Expected{}.ComparisonOperator", Kind: modelcheck.KindEnum, Enum: []string{"NOT_CONTAINS", "BEGINS_WITH", "NE", "IN", "LE", "LT", "GE", "GT", "NOT_NULL", "NULL", "EQ", "BETWEEN", "CONTAINS"}},
		{Path: "ExpressionAttributeNames{}", Kind: modelcheck.KindLength, Min: 0, Max: 65535},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "ReturnConsumedCapacity", Kind: modelcheck.KindEnum, Enum: []string{"INDEXES", "TOTAL", "NONE"}},
		{Path: "ReturnItemCollectionMetrics", Kind: modelcheck.KindEnum, Enum: []string{"SIZE", "NONE"}},
		{Path: "ReturnValues", Kind: modelcheck.KindEnum, Enum: []string{"UPDATED_NEW", "NONE", "ALL_OLD", "UPDATED_OLD", "ALL_NEW"}},
		{Path: "ReturnValuesOnConditionCheckFailure", Kind: modelcheck.KindEnum, Enum: []string{"ALL_OLD", "NONE"}},
		{Path: "TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TableName", Kind: modelcheck.KindRequired},
	},
	"DeleteTable": {
		{Path: "TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TableName", Kind: modelcheck.KindRequired},
	},
	"DescribeContinuousBackups": {
		{Path: "TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TableName", Kind: modelcheck.KindRequired},
	},
	"DescribeContributorInsights": {
		{Path: "IndexName", Kind: modelcheck.KindLength, Min: 3, Max: 255},
		{Path: "IndexName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TableName", Kind: modelcheck.KindRequired},
	},
	"DescribeTable": {
		{Path: "TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TableName", Kind: modelcheck.KindRequired},
	},
	"DescribeTimeToLive": {
		{Path: "TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TableName", Kind: modelcheck.KindRequired},
	},
	"ExecuteStatement": {
		{Path: "Limit", Kind: modelcheck.KindRange, Min: 1, Max: modelcheck.NoMax},
		{Path: "NextToken", Kind: modelcheck.KindLength, Min: 1, Max: 32768},
		{Path: "ReturnConsumedCapacity", Kind: modelcheck.KindEnum, Enum: []string{"INDEXES", "TOTAL", "NONE"}},
		{Path: "ReturnValuesOnConditionCheckFailure", Kind: modelcheck.KindEnum, Enum: []string{"ALL_OLD", "NONE"}},
		{Path: "Statement", Kind: modelcheck.KindLength, Min: 1, Max: 8192},
		{Path: "Statement", Kind: modelcheck.KindRequired},
	},
	"ExecuteTransaction": {
		{Path: "ClientRequestToken", Kind: modelcheck.KindLength, Min: 1, Max: 36},
		{Path: "ReturnConsumedCapacity", Kind: modelcheck.KindEnum, Enum: []string{"INDEXES", "TOTAL", "NONE"}},
		{Path: "TransactStatements", Kind: modelcheck.KindRequired},
		{Path: "TransactStatements[].ReturnValuesOnConditionCheckFailure", Kind: modelcheck.KindEnum, Enum: []string{"ALL_OLD", "NONE"}},
		{Path: "TransactStatements[].Statement", Kind: modelcheck.KindLength, Min: 1, Max: 8192},
		{Path: "TransactStatements[].Statement", Kind: modelcheck.KindRequired},
	},
	"GetItem": {
		{Path: "AttributesToGet[]", Kind: modelcheck.KindLength, Min: 0, Max: 65535},
		{Path: "ExpressionAttributeNames{}", Kind: modelcheck.KindLength, Min: 0, Max: 65535},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "ReturnConsumedCapacity", Kind: modelcheck.KindEnum, Enum: []string{"INDEXES", "TOTAL", "NONE"}},
		{Path: "TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TableName", Kind: modelcheck.KindRequired},
	},
	"ListTables": {
		{Path: "ExclusiveStartTableName", Kind: modelcheck.KindLength, Min: 3, Max: 255},
		{Path: "ExclusiveStartTableName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "Limit", Kind: modelcheck.KindRange, Min: 1, Max: 100},
	},
	"ListTagsOfResource": {
		{Path: "ResourceArn", Kind: modelcheck.KindLength, Min: 1, Max: 1283},
		{Path: "ResourceArn", Kind: modelcheck.KindRequired},
	},
	"PutItem": {
		{Path: "ConditionalOperator", Kind: modelcheck.KindEnum, Enum: []string{"AND", "OR"}},
		{Path: "Expected{}.ComparisonOperator", Kind: modelcheck.KindEnum, Enum: []string{"EQ", "BETWEEN", "CONTAINS", "NOT_CONTAINS", "BEGINS_WITH", "NE", "IN", "LE", "LT", "GE", "GT", "NOT_NULL", "NULL"}},
		{Path: "ExpressionAttributeNames{}", Kind: modelcheck.KindLength, Min: 0, Max: 65535},
		{Path: "Item", Kind: modelcheck.KindRequired},
		{Path: "ReturnConsumedCapacity", Kind: modelcheck.KindEnum, Enum: []string{"INDEXES", "TOTAL", "NONE"}},
		{Path: "ReturnItemCollectionMetrics", Kind: modelcheck.KindEnum, Enum: []string{"SIZE", "NONE"}},
		{Path: "ReturnValues", Kind: modelcheck.KindEnum, Enum: []string{"ALL_NEW", "UPDATED_NEW", "NONE", "ALL_OLD", "UPDATED_OLD"}},
		{Path: "ReturnValuesOnConditionCheckFailure", Kind: modelcheck.KindEnum, Enum: []string{"ALL_OLD", "NONE"}},
		{Path: "TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TableName", Kind: modelcheck.KindRequired},
	},
	"Query": {
		{Path: "AttributesToGet[]", Kind: modelcheck.KindLength, Min: 0, Max: 65535},
		{Path: "ConditionalOperator", Kind: modelcheck.KindEnum, Enum: []string{"AND", "OR"}},
		{Path: "ExpressionAttributeNames{}", Kind: modelcheck.KindLength, Min: 0, Max: 65535},
		{Path: "IndexName", Kind: modelcheck.KindLength, Min: 3, Max: 255},
		{Path: "IndexName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "KeyConditions{}.ComparisonOperator", Kind: modelcheck.KindEnum, Enum: []string{"NE", "IN", "LE", "LT", "GE", "GT", "NOT_NULL", "NULL", "EQ", "BETWEEN", "CONTAINS", "NOT_CONTAINS", "BEGINS_WITH"}},
		{Path: "KeyConditions{}.ComparisonOperator", Kind: modelcheck.KindRequired},
		{Path: "Limit", Kind: modelcheck.KindRange, Min: 1, Max: modelcheck.NoMax},
		{Path: "QueryFilter{}.ComparisonOperator", Kind: modelcheck.KindEnum, Enum: []string{"NE", "IN", "LE", "LT", "GE", "GT", "NOT_NULL", "NULL", "EQ", "BETWEEN", "CONTAINS", "NOT_CONTAINS", "BEGINS_WITH"}},
		{Path: "QueryFilter{}.ComparisonOperator", Kind: modelcheck.KindRequired},
		{Path: "ReturnConsumedCapacity", Kind: modelcheck.KindEnum, Enum: []string{"INDEXES", "TOTAL", "NONE"}},
		{Path: "Select", Kind: modelcheck.KindEnum, Enum: []string{"ALL_ATTRIBUTES", "ALL_PROJECTED_ATTRIBUTES", "SPECIFIC_ATTRIBUTES", "COUNT"}},
		{Path: "TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TableName", Kind: modelcheck.KindRequired},
	},
	"Scan": {
		{Path: "AttributesToGet[]", Kind: modelcheck.KindLength, Min: 0, Max: 65535},
		{Path: "ConditionalOperator", Kind: modelcheck.KindEnum, Enum: []string{"OR", "AND"}},
		{Path: "ExpressionAttributeNames{}", Kind: modelcheck.KindLength, Min: 0, Max: 65535},
		{Path: "IndexName", Kind: modelcheck.KindLength, Min: 3, Max: 255},
		{Path: "IndexName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "Limit", Kind: modelcheck.KindRange, Min: 1, Max: modelcheck.NoMax},
		{Path: "ReturnConsumedCapacity", Kind: modelcheck.KindEnum, Enum: []string{"INDEXES", "TOTAL", "NONE"}},
		{Path: "ScanFilter{}.ComparisonOperator", Kind: modelcheck.KindEnum, Enum: []string{"CONTAINS", "NOT_CONTAINS", "BEGINS_WITH", "NE", "IN", "LE", "LT", "GE", "GT", "NOT_NULL", "NULL", "EQ", "BETWEEN"}},
		{Path: "ScanFilter{}.ComparisonOperator", Kind: modelcheck.KindRequired},
		{Path: "Segment", Kind: modelcheck.KindRange, Min: 0, Max: 999999},
		{Path: "Select", Kind: modelcheck.KindEnum, Enum: []string{"ALL_ATTRIBUTES", "ALL_PROJECTED_ATTRIBUTES", "SPECIFIC_ATTRIBUTES", "COUNT"}},
		{Path: "TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TableName", Kind: modelcheck.KindRequired},
		{Path: "TotalSegments", Kind: modelcheck.KindRange, Min: 1, Max: 1000000},
	},
	"TagResource": {
		{Path: "ResourceArn", Kind: modelcheck.KindLength, Min: 1, Max: 1283},
		{Path: "ResourceArn", Kind: modelcheck.KindRequired},
		{Path: "Tags", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Key", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Tags[].Key", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Value", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Tags[].Value", Kind: modelcheck.KindRequired},
	},
	"TransactGetItems": {
		{Path: "ReturnConsumedCapacity", Kind: modelcheck.KindEnum, Enum: []string{"INDEXES", "TOTAL", "NONE"}},
		{Path: "TransactItems", Kind: modelcheck.KindRequired},
		{Path: "TransactItems[].Get", Kind: modelcheck.KindRequired},
		{Path: "TransactItems[].Get.Key", Kind: modelcheck.KindRequired},
		{Path: "TransactItems[].Get.TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TransactItems[].Get.TableName", Kind: modelcheck.KindRequired},
	},
	"TransactWriteItems": {
		{Path: "ClientRequestToken", Kind: modelcheck.KindLength, Min: 1, Max: 36},
		{Path: "ReturnConsumedCapacity", Kind: modelcheck.KindEnum, Enum: []string{"TOTAL", "NONE", "INDEXES"}},
		{Path: "ReturnItemCollectionMetrics", Kind: modelcheck.KindEnum, Enum: []string{"SIZE", "NONE"}},
		{Path: "TransactItems", Kind: modelcheck.KindRequired},
		{Path: "TransactItems[].ConditionCheck.ConditionExpression", Kind: modelcheck.KindRequired},
		{Path: "TransactItems[].ConditionCheck.Key", Kind: modelcheck.KindRequired},
		{Path: "TransactItems[].ConditionCheck.ReturnValuesOnConditionCheckFailure", Kind: modelcheck.KindEnum, Enum: []string{"ALL_OLD", "NONE"}},
		{Path: "TransactItems[].ConditionCheck.TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TransactItems[].ConditionCheck.TableName", Kind: modelcheck.KindRequired},
		{Path: "TransactItems[].Delete.Key", Kind: modelcheck.KindRequired},
		{Path: "TransactItems[].Delete.ReturnValuesOnConditionCheckFailure", Kind: modelcheck.KindEnum, Enum: []string{"ALL_OLD", "NONE"}},
		{Path: "TransactItems[].Delete.TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TransactItems[].Delete.TableName", Kind: modelcheck.KindRequired},
		{Path: "TransactItems[].Put.Item", Kind: modelcheck.KindRequired},
		{Path: "TransactItems[].Put.ReturnValuesOnConditionCheckFailure", Kind: modelcheck.KindEnum, Enum: []string{"ALL_OLD", "NONE"}},
		{Path: "TransactItems[].Put.TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TransactItems[].Put.TableName", Kind: modelcheck.KindRequired},
		{Path: "TransactItems[].Update.Key", Kind: modelcheck.KindRequired},
		{Path: "TransactItems[].Update.ReturnValuesOnConditionCheckFailure", Kind: modelcheck.KindEnum, Enum: []string{"ALL_OLD", "NONE"}},
		{Path: "TransactItems[].Update.TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TransactItems[].Update.TableName", Kind: modelcheck.KindRequired},
		{Path: "TransactItems[].Update.UpdateExpression", Kind: modelcheck.KindRequired},
	},
	"UntagResource": {
		{Path: "ResourceArn", Kind: modelcheck.KindLength, Min: 1, Max: 1283},
		{Path: "ResourceArn", Kind: modelcheck.KindRequired},
		{Path: "TagKeys", Kind: modelcheck.KindRequired},
		{Path: "TagKeys[]", Kind: modelcheck.KindLength, Min: 1, Max: 128},
	},
	"UpdateContinuousBackups": {
		{Path: "PointInTimeRecoverySpecification", Kind: modelcheck.KindRequired},
		{Path: "PointInTimeRecoverySpecification.PointInTimeRecoveryEnabled", Kind: modelcheck.KindRequired},
		{Path: "PointInTimeRecoverySpecification.RecoveryPeriodInDays", Kind: modelcheck.KindRange, Min: 1, Max: 35},
		{Path: "TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TableName", Kind: modelcheck.KindRequired},
	},
	"UpdateContributorInsights": {
		{Path: "ContributorInsightsAction", Kind: modelcheck.KindEnum, Enum: []string{"ENABLE", "DISABLE"}},
		{Path: "ContributorInsightsAction", Kind: modelcheck.KindRequired},
		{Path: "ContributorInsightsMode", Kind: modelcheck.KindEnum, Enum: []string{"ACCESSED_AND_THROTTLED_KEYS", "THROTTLED_KEYS"}},
		{Path: "IndexName", Kind: modelcheck.KindLength, Min: 3, Max: 255},
		{Path: "IndexName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TableName", Kind: modelcheck.KindRequired},
	},
	"UpdateItem": {
		{Path: "AttributeUpdates{}.Action", Kind: modelcheck.KindEnum, Enum: []string{"DELETE", "ADD", "PUT"}},
		{Path: "ConditionalOperator", Kind: modelcheck.KindEnum, Enum: []string{"AND", "OR"}},
		{Path: "Expected{}.ComparisonOperator", Kind: modelcheck.KindEnum, Enum: []string{"IN", "LE", "LT", "GE", "GT", "NOT_NULL", "NULL", "EQ", "BETWEEN", "CONTAINS", "NOT_CONTAINS", "BEGINS_WITH", "NE"}},
		{Path: "ExpressionAttributeNames{}", Kind: modelcheck.KindLength, Min: 0, Max: 65535},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "ReturnConsumedCapacity", Kind: modelcheck.KindEnum, Enum: []string{"INDEXES", "TOTAL", "NONE"}},
		{Path: "ReturnItemCollectionMetrics", Kind: modelcheck.KindEnum, Enum: []string{"SIZE", "NONE"}},
		{Path: "ReturnValues", Kind: modelcheck.KindEnum, Enum: []string{"UPDATED_NEW", "NONE", "ALL_OLD", "UPDATED_OLD", "ALL_NEW"}},
		{Path: "ReturnValuesOnConditionCheckFailure", Kind: modelcheck.KindEnum, Enum: []string{"NONE", "ALL_OLD"}},
		{Path: "TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TableName", Kind: modelcheck.KindRequired},
	},
	"UpdateTable": {
		{Path: "AttributeDefinitions[].AttributeName", Kind: modelcheck.KindLength, Min: 1, Max: 255},
		{Path: "AttributeDefinitions[].AttributeName", Kind: modelcheck.KindRequired},
		{Path: "AttributeDefinitions[].AttributeType", Kind: modelcheck.KindEnum, Enum: []string{"S", "N", "B"}},
		{Path: "AttributeDefinitions[].AttributeType", Kind: modelcheck.KindRequired},
		{Path: "BillingMode", Kind: modelcheck.KindEnum, Enum: []string{"PROVISIONED", "PAY_PER_REQUEST"}},
		{Path: "GlobalSecondaryIndexUpdates[].Create.IndexName", Kind: modelcheck.KindLength, Min: 3, Max: 255},
		{Path: "GlobalSecondaryIndexUpdates[].Create.IndexName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "GlobalSecondaryIndexUpdates[].Create.IndexName", Kind: modelcheck.KindRequired},
		{Path: "GlobalSecondaryIndexUpdates[].Create.KeySchema", Kind: modelcheck.KindRequired},
		{Path: "GlobalSecondaryIndexUpdates[].Create.Projection", Kind: modelcheck.KindRequired},
		{Path: "GlobalSecondaryIndexUpdates[].Create.ProvisionedThroughput.ReadCapacityUnits", Kind: modelcheck.KindRequired},
		{Path: "GlobalSecondaryIndexUpdates[].Create.ProvisionedThroughput.WriteCapacityUnits", Kind: modelcheck.KindRequired},
		{Path: "GlobalSecondaryIndexUpdates[].Delete.IndexName", Kind: modelcheck.KindLength, Min: 3, Max: 255},
		{Path: "GlobalSecondaryIndexUpdates[].Delete.IndexName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "GlobalSecondaryIndexUpdates[].Delete.IndexName", Kind: modelcheck.KindRequired},
		{Path: "GlobalSecondaryIndexUpdates[].Update.IndexName", Kind: modelcheck.KindLength, Min: 3, Max: 255},
		{Path: "GlobalSecondaryIndexUpdates[].Update.IndexName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "GlobalSecondaryIndexUpdates[].Update.IndexName", Kind: modelcheck.KindRequired},
		{Path: "GlobalSecondaryIndexUpdates[].Update.ProvisionedThroughput.ReadCapacityUnits", Kind: modelcheck.KindRequired},
		{Path: "GlobalSecondaryIndexUpdates[].Update.ProvisionedThroughput.WriteCapacityUnits", Kind: modelcheck.KindRequired},
		{Path: "GlobalTableSettingsReplicationMode", Kind: modelcheck.KindEnum, Enum: []string{"ENABLED", "DISABLED", "ENABLED_WITH_OVERRIDES"}},
		{Path: "GlobalTableWitnessUpdates[].Create.RegionName", Kind: modelcheck.KindRequired},
		{Path: "GlobalTableWitnessUpdates[].Delete.RegionName", Kind: modelcheck.KindRequired},
		{Path: "MultiRegionConsistency", Kind: modelcheck.KindEnum, Enum: []string{"EVENTUAL", "STRONG"}},
		{Path: "ProvisionedThroughput.ReadCapacityUnits", Kind: modelcheck.KindRange, Min: 1, Max: modelcheck.NoMax},
		{Path: "ProvisionedThroughput.ReadCapacityUnits", Kind: modelcheck.KindRequired},
		{Path: "ProvisionedThroughput.WriteCapacityUnits", Kind: modelcheck.KindRange, Min: 1, Max: modelcheck.NoMax},
		{Path: "ProvisionedThroughput.WriteCapacityUnits", Kind: modelcheck.KindRequired},
		{Path: "ReplicaUpdates[].Create.RegionName", Kind: modelcheck.KindRequired},
		{Path: "ReplicaUpdates[].Create.TableClassOverride", Kind: modelcheck.KindEnum, Enum: []string{"STANDARD", "STANDARD_INFREQUENT_ACCESS"}},
		{Path: "ReplicaUpdates[].Delete.RegionName", Kind: modelcheck.KindRequired},
		{Path: "ReplicaUpdates[].Update.RegionName", Kind: modelcheck.KindRequired},
		{Path: "ReplicaUpdates[].Update.TableClassOverride", Kind: modelcheck.KindEnum, Enum: []string{"STANDARD_INFREQUENT_ACCESS", "STANDARD"}},
		{Path: "SSESpecification.SSEType", Kind: modelcheck.KindEnum, Enum: []string{"AES256", "KMS"}},
		{Path: "StreamSpecification.StreamEnabled", Kind: modelcheck.KindRequired},
		{Path: "StreamSpecification.StreamViewType", Kind: modelcheck.KindEnum, Enum: []string{"NEW_AND_OLD_IMAGES", "KEYS_ONLY", "NEW_IMAGE", "OLD_IMAGE"}},
		{Path: "TableClass", Kind: modelcheck.KindEnum, Enum: []string{"STANDARD", "STANDARD_INFREQUENT_ACCESS"}},
		{Path: "TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TableName", Kind: modelcheck.KindRequired},
		{Path: "VectorIndexUpdates[].Create.Dimensions", Kind: modelcheck.KindRange, Min: 1, Max: modelcheck.NoMax},
		{Path: "VectorIndexUpdates[].Create.Dimensions", Kind: modelcheck.KindRequired},
		{Path: "VectorIndexUpdates[].Create.DistanceFunction", Kind: modelcheck.KindEnum, Enum: []string{"COSINE", "DOT_PRODUCT", "EUCLIDEAN"}},
		{Path: "VectorIndexUpdates[].Create.DistanceFunction", Kind: modelcheck.KindRequired},
		{Path: "VectorIndexUpdates[].Create.IndexName", Kind: modelcheck.KindLength, Min: 3, Max: 255},
		{Path: "VectorIndexUpdates[].Create.IndexName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "VectorIndexUpdates[].Create.IndexName", Kind: modelcheck.KindRequired},
		{Path: "VectorIndexUpdates[].Create.Projection", Kind: modelcheck.KindRequired},
		{Path: "VectorIndexUpdates[].Create.VectorAttribute", Kind: modelcheck.KindRequired},
		{Path: "VectorIndexUpdates[].Create.VectorAttribute.AttributeName", Kind: modelcheck.KindRequired},
		{Path: "VectorIndexUpdates[].Delete.IndexName", Kind: modelcheck.KindLength, Min: 3, Max: 255},
		{Path: "VectorIndexUpdates[].Delete.IndexName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "VectorIndexUpdates[].Delete.IndexName", Kind: modelcheck.KindRequired},
	},
	"UpdateTimeToLive": {
		{Path: "TableName", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "TableName", Kind: modelcheck.KindRequired},
		{Path: "TimeToLiveSpecification", Kind: modelcheck.KindRequired},
		{Path: "TimeToLiveSpecification.AttributeName", Kind: modelcheck.KindLength, Min: 1, Max: 255},
		{Path: "TimeToLiveSpecification.AttributeName", Kind: modelcheck.KindRequired},
		{Path: "TimeToLiveSpecification.Enabled", Kind: modelcheck.KindRequired},
	},
}
