package kinesis

// Kinesis's model-derived input validation: the constraint tables, walked by
// internal/modelcheck.
//
// Generated from AWS's own service model with `dzaudit cases kinesis` rather
// than transcribed, and replayed case by case in
// kinesis/rejection_parity_test.go. An operation missing from this map either
// states no constraints on its inputs or is one doze-aws does not dispatch —
// the latter refuses every request including a valid one, so replaying a
// mutation against it proves nothing.

import (
	"regexp"

	"github.com/doze-dev/doze-aws/internal/modelcheck"
)

var constraintTables = map[string][]modelcheck.Constraint{
	"AddTagsToStream": {
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "Tags", Kind: modelcheck.KindRequired},
		{Path: "Tags{}", Kind: modelcheck.KindLength, Min: 0, Max: 256},
	},
	"CreateStream": {
		{Path: "MaxRecordSizeInKiB", Kind: modelcheck.KindRange, Min: 1024, Max: 10240},
		{Path: "ShardCount", Kind: modelcheck.KindRange, Min: 1, Max: modelcheck.NoMax},
		{Path: "StreamModeDetails.StreamMode", Kind: modelcheck.KindEnum, Enum: []string{"PROVISIONED", "ON_DEMAND"}},
		{Path: "StreamModeDetails.StreamMode", Kind: modelcheck.KindRequired},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "StreamName", Kind: modelcheck.KindRequired},
		{Path: "Tags{}", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "WarmThroughputMiBps", Kind: modelcheck.KindRange, Min: 0, Max: modelcheck.NoMax},
	},
	"DecreaseStreamRetentionPeriod": {
		{Path: "RetentionPeriodHours", Kind: modelcheck.KindRequired},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
	},
	"DeleteResourcePolicy": {
		{Path: "ResourceARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "ResourceARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:.*stream/\S+$`)},
		{Path: "ResourceARN", Kind: modelcheck.KindRequired},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
	},
	"DeleteStream": {
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
	},
	"DeregisterStreamConsumer": {
		{Path: "ConsumerARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "ConsumerARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn):aws.*:kinesis:.*:\d{12}:.*stream\/[a-zA-Z0-9_.-]+\/consumer\/[a-zA-Z0-9_.-]+:[0-9]+$`)},
		{Path: "ConsumerName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "ConsumerName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
	},
	"DescribeStream": {
		{Path: "ExclusiveStartShardId", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "ExclusiveStartShardId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "Limit", Kind: modelcheck.KindRange, Min: 1, Max: 10000},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
	},
	"DescribeStreamConsumer": {
		{Path: "ConsumerARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "ConsumerARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn):aws.*:kinesis:.*:\d{12}:.*stream\/[a-zA-Z0-9_.-]+\/consumer\/[a-zA-Z0-9_.-]+:[0-9]+$`)},
		{Path: "ConsumerName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "ConsumerName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
	},
	"DescribeStreamSummary": {
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
	},
	"DisableEnhancedMonitoring": {
		{Path: "ShardLevelMetrics", Kind: modelcheck.KindRequired},
		{Path: "ShardLevelMetrics[]", Kind: modelcheck.KindEnum, Enum: []string{"OutgoingBytes", "OutgoingRecords", "WriteProvisionedThroughputExceeded", "ReadProvisionedThroughputExceeded", "IteratorAgeMilliseconds", "ALL", "IncomingBytes", "IncomingRecords"}},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
	},
	"EnableEnhancedMonitoring": {
		{Path: "ShardLevelMetrics", Kind: modelcheck.KindRequired},
		{Path: "ShardLevelMetrics[]", Kind: modelcheck.KindEnum, Enum: []string{"OutgoingBytes", "OutgoingRecords", "WriteProvisionedThroughputExceeded", "ReadProvisionedThroughputExceeded", "IteratorAgeMilliseconds", "ALL", "IncomingBytes", "IncomingRecords"}},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
	},
	"GetRecords": {
		{Path: "Limit", Kind: modelcheck.KindRange, Min: 1, Max: 10000},
		{Path: "ShardIterator", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "ShardIterator", Kind: modelcheck.KindRequired},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
	},
	"GetResourcePolicy": {
		{Path: "ResourceARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "ResourceARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:.*stream/\S+$`)},
		{Path: "ResourceARN", Kind: modelcheck.KindRequired},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
	},
	"GetShardIterator": {
		{Path: "ShardId", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "ShardId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "ShardId", Kind: modelcheck.KindRequired},
		{Path: "ShardIteratorType", Kind: modelcheck.KindEnum, Enum: []string{"LATEST", "AT_TIMESTAMP", "AT_SEQUENCE_NUMBER", "AFTER_SEQUENCE_NUMBER", "TRIM_HORIZON"}},
		{Path: "ShardIteratorType", Kind: modelcheck.KindRequired},
		{Path: "StartingSequenceNumber", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^0|([1-9]\d{0,128})$`)},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
	},
	"IncreaseStreamRetentionPeriod": {
		{Path: "RetentionPeriodHours", Kind: modelcheck.KindRequired},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
	},
	"ListShards": {
		{Path: "ExclusiveStartShardId", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "ExclusiveStartShardId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "MaxResults", Kind: modelcheck.KindRange, Min: 1, Max: 10000},
		{Path: "NextToken", Kind: modelcheck.KindLength, Min: 1, Max: 1048576},
		{Path: "ShardFilter.ShardId", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "ShardFilter.ShardId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "ShardFilter.Type", Kind: modelcheck.KindEnum, Enum: []string{"AT_TRIM_HORIZON", "FROM_TRIM_HORIZON", "AT_LATEST", "AT_TIMESTAMP", "FROM_TIMESTAMP", "AFTER_SHARD_ID"}},
		{Path: "ShardFilter.Type", Kind: modelcheck.KindRequired},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
	},
	"ListStreamConsumers": {
		{Path: "MaxResults", Kind: modelcheck.KindRange, Min: 1, Max: 10000},
		{Path: "NextToken", Kind: modelcheck.KindLength, Min: 1, Max: 1048576},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamARN", Kind: modelcheck.KindRequired},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
	},
	"ListStreams": {
		{Path: "ExclusiveStartStreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "ExclusiveStartStreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "Limit", Kind: modelcheck.KindRange, Min: 1, Max: 10000},
		{Path: "NextToken", Kind: modelcheck.KindLength, Min: 1, Max: 1048576},
	},
	"ListTagsForResource": {
		{Path: "ResourceARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "ResourceARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:.*stream/\S+$`)},
		{Path: "ResourceARN", Kind: modelcheck.KindRequired},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
	},
	"ListTagsForStream": {
		{Path: "ExclusiveStartTagKey", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Limit", Kind: modelcheck.KindRange, Min: 1, Max: 50},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
	},
	"MergeShards": {
		{Path: "AdjacentShardToMerge", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "AdjacentShardToMerge", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "AdjacentShardToMerge", Kind: modelcheck.KindRequired},
		{Path: "ShardToMerge", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "ShardToMerge", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "ShardToMerge", Kind: modelcheck.KindRequired},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
	},
	"PutRecord": {
		{Path: "Data", Kind: modelcheck.KindLength, Min: 0, Max: 10485760},
		{Path: "Data", Kind: modelcheck.KindRequired},
		{Path: "ExplicitHashKey", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^0|([1-9]\d{0,38})$`)},
		{Path: "PartitionKey", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "PartitionKey", Kind: modelcheck.KindRequired},
		{Path: "SequenceNumberForOrdering", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^0|([1-9]\d{0,128})$`)},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
	},
	"PutRecords": {
		{Path: "Records", Kind: modelcheck.KindRequired},
		{Path: "Records[].Data", Kind: modelcheck.KindLength, Min: 0, Max: 10485760},
		{Path: "Records[].Data", Kind: modelcheck.KindRequired},
		{Path: "Records[].ExplicitHashKey", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^0|([1-9]\d{0,38})$`)},
		{Path: "Records[].PartitionKey", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "Records[].PartitionKey", Kind: modelcheck.KindRequired},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
	},
	"PutResourcePolicy": {
		{Path: "Policy", Kind: modelcheck.KindRequired},
		{Path: "ResourceARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "ResourceARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:.*stream/\S+$`)},
		{Path: "ResourceARN", Kind: modelcheck.KindRequired},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
	},
	"RegisterStreamConsumer": {
		{Path: "ConsumerName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "ConsumerName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "ConsumerName", Kind: modelcheck.KindRequired},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamARN", Kind: modelcheck.KindRequired},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "Tags{}", Kind: modelcheck.KindLength, Min: 0, Max: 256},
	},
	"RemoveTagsFromStream": {
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "TagKeys", Kind: modelcheck.KindRequired},
		{Path: "TagKeys[]", Kind: modelcheck.KindLength, Min: 1, Max: 128},
	},
	"SplitShard": {
		{Path: "NewStartingHashKey", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^0|([1-9]\d{0,38})$`)},
		{Path: "NewStartingHashKey", Kind: modelcheck.KindRequired},
		{Path: "ShardToSplit", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "ShardToSplit", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "ShardToSplit", Kind: modelcheck.KindRequired},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
	},
	"StartStreamEncryption": {
		{Path: "EncryptionType", Kind: modelcheck.KindEnum, Enum: []string{"NONE", "KMS"}},
		{Path: "EncryptionType", Kind: modelcheck.KindRequired},
		{Path: "KeyId", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "KeyId", Kind: modelcheck.KindRequired},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
	},
	"StopStreamEncryption": {
		{Path: "EncryptionType", Kind: modelcheck.KindEnum, Enum: []string{"NONE", "KMS"}},
		{Path: "EncryptionType", Kind: modelcheck.KindRequired},
		{Path: "KeyId", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "KeyId", Kind: modelcheck.KindRequired},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
	},
	"TagResource": {
		{Path: "ResourceARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "ResourceARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:.*stream/\S+$`)},
		{Path: "ResourceARN", Kind: modelcheck.KindRequired},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "Tags", Kind: modelcheck.KindRequired},
		{Path: "Tags{}", Kind: modelcheck.KindLength, Min: 0, Max: 256},
	},
	"UntagResource": {
		{Path: "ResourceARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "ResourceARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:.*stream/\S+$`)},
		{Path: "ResourceARN", Kind: modelcheck.KindRequired},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "TagKeys", Kind: modelcheck.KindRequired},
		{Path: "TagKeys[]", Kind: modelcheck.KindLength, Min: 1, Max: 128},
	},
	"UpdateAccountSettings": {
		{Path: "MinimumThroughputBillingCommitment", Kind: modelcheck.KindRequired},
		{Path: "MinimumThroughputBillingCommitment.Status", Kind: modelcheck.KindEnum, Enum: []string{"ENABLED", "DISABLED"}},
		{Path: "MinimumThroughputBillingCommitment.Status", Kind: modelcheck.KindRequired},
	},
	"UpdateMaxRecordSize": {
		{Path: "MaxRecordSizeInKiB", Kind: modelcheck.KindRange, Min: 1024, Max: 10240},
		{Path: "MaxRecordSizeInKiB", Kind: modelcheck.KindRequired},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
	},
	"UpdateShardCount": {
		{Path: "ScalingType", Kind: modelcheck.KindEnum, Enum: []string{"UNIFORM_SCALING"}},
		{Path: "ScalingType", Kind: modelcheck.KindRequired},
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "StreamName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)},
		{Path: "TargetShardCount", Kind: modelcheck.KindRange, Min: 1, Max: modelcheck.NoMax},
		{Path: "TargetShardCount", Kind: modelcheck.KindRequired},
	},
	"UpdateStreamMode": {
		{Path: "StreamARN", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "StreamARN", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`)},
		{Path: "StreamARN", Kind: modelcheck.KindRequired},
		{Path: "StreamId", Kind: modelcheck.KindLength, Min: 1, Max: 24},
		{Path: "StreamId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-z0-9]{20}-[a-z0-9]{3}$`)},
		{Path: "StreamModeDetails", Kind: modelcheck.KindRequired},
		{Path: "StreamModeDetails.StreamMode", Kind: modelcheck.KindEnum, Enum: []string{"PROVISIONED", "ON_DEMAND"}},
		{Path: "StreamModeDetails.StreamMode", Kind: modelcheck.KindRequired},
		{Path: "WarmThroughputMiBps", Kind: modelcheck.KindRange, Min: 0, Max: modelcheck.NoMax},
	},
}
