package cloudwatch_test

// Rejection parity: does doze-aws refuse what CloudWatch refuses?
//
// The cases are generated by `dzaudit cases cloudwatch` from AWS's own service
// model and committed to testdata/, so the checklist is not something anyone
// remembered to write. Each case names one constrained input and a value that
// violates it.
//
// # The trap this is built around
//
// A request refused for the WRONG reason looks exactly like a pass. Send a
// PutMetricData with a bad Unit and no Namespace and it is refused — for the
// missing namespace — and a runner that only asks "was it refused" records a
// validation that does not exist. So every case is a mutation OF a baseline
// the test first proves the service ACCEPTS. A baseline that fails is
// reported as unusable, not as a pass.
//
// # Three wires, one fixture
//
// Every case is replayed over all three protocols. The constraint table is
// written once against the JSON shape, and CBOR and Query are normalised into
// it, so a case that refuses on one wire and not another means the
// normalisation is lying — which is exactly the class of bug that made the
// Query lane drop list elements. Nothing else here has three chances to be
// wrong, so nothing else gets this treatment.

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/doze-dev/doze-aws/awsident"
	"github.com/doze-dev/doze-aws/cloudwatch"
	"github.com/doze-dev/doze-aws/internal/auditkit"
	"github.com/doze-dev/doze-aws/internal/rpcv2cbor"
)

type auditCase struct {
	Operation   string           `json:"operation"`
	Target      string           `json:"target"`
	Path        string           `json:"path"`
	Why         string           `json:"why"`
	Value       any              `json:"value"`
	ValueRepeat *auditkit.Repeat `json:"value_repeat,omitempty"`
	Constraint  string           `json:"constraint"`
}

// dispatched is the set of operations with a real handler. A case against a
// refused operation proves nothing — it answers UnsupportedOperationException
// whatever the input — so replaying one would be a case that cannot fail.
//
// Derived from the dispatch table itself: this was a hand-written list, and
// it silently excluded every alarm operation from the day they landed.
var dispatched = cloudwatch.Dispatched()

func loadCases(t *testing.T) []auditCase {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "cases_cloudwatch.json"))
	if err != nil {
		t.Fatal(err)
	}
	var all []auditCase
	if err := json.Unmarshal(raw, &all); err != nil {
		t.Fatal(err)
	}
	var cs []auditCase
	for _, c := range all {
		// A max-length case stores the shape of its padding, not the run.
		c.Value = auditkit.Materialize(c.Value, c.ValueRepeat)
		if dispatched[c.Operation] {
			cs = append(cs, c)
		}
	}
	if len(cs) == 0 {
		t.Fatal("no cases: the audit would pass vacuously")
	}
	return cs
}

// baselines is one request per dispatched operation that the service is
// expected to accept. Everything below is a mutation of one of these.
func baselines() map[string]map[string]any {
	from := "2026-09-10T11:00:00Z"
	to := "2026-09-10T12:00:00Z"
	return map[string]map[string]any{
		"PutMetricData": {
			"Namespace": "Audit",
			"MetricData": []any{map[string]any{
				"MetricName": "Probe",
				"Value":      1.0,
				"Unit":       "Count",
				"Dimensions": []any{map[string]any{"Name": "Stage", "Value": "prod"}},
			}},
		},
		"ListMetrics": {
			"Namespace": "Audit",
		},
		"GetMetricStatistics": {
			"Namespace": "Audit", "MetricName": "Probe",
			"StartTime": from, "EndTime": to,
			"Period":     60.0,
			"Statistics": []any{"Sum"},
			"Dimensions": []any{map[string]any{"Name": "Stage", "Value": "prod"}},
		},
		"GetMetricData": {
			"StartTime": from, "EndTime": to,
			"MetricDataQueries": []any{map[string]any{
				"Id": "q1",
				"MetricStat": map[string]any{
					"Metric": map[string]any{"Namespace": "Audit", "MetricName": "Probe"},
					"Period": 60.0,
					"Stat":   "Sum",
				},
			}},
		},

		// The alarm operations. They have had model-derived cases in the
		// fixture since D3 and no baseline to mutate, so none of them ran.
		"PutMetricAlarm": {
			"AlarmName": auditAlarm, "Namespace": "Audit", "MetricName": "Probe",
			"Statistic": "Sum", "Period": 60.0, "EvaluationPeriods": 1.0,
			"ComparisonOperator": "GreaterThanThreshold", "Threshold": 1.0,
			"Dimensions": []any{map[string]any{"Name": "Stage", "Value": "prod"}},
		},
		"DescribeAlarms":          {},
		"DescribeAlarmsForMetric": {"Namespace": "Audit", "MetricName": "Probe"},
		"DescribeAlarmHistory":    {"AlarmName": auditAlarm},
		"SetAlarmState": {
			"AlarmName": auditAlarm, "StateValue": "ALARM", "StateReason": "by hand",
		},
		"EnableAlarmActions":  {"AlarmNames": []any{auditAlarm}},
		"DisableAlarmActions": {"AlarmNames": []any{auditAlarm}},
		// DeleteAlarms consumes what it names, so it gets its own alarm —
		// seeded per case by prepare, not the shared one every other alarm
		// operation reads.
		"DeleteAlarms": {"AlarmNames": []any{auditDoomedAlarm}},

		// Dashboards and tags.
		"PutDashboard": {
			"DashboardName": auditDashboard,
			"DashboardBody": `{"widgets":[]}`,
		},
		"GetDashboard":     {"DashboardName": auditDashboard},
		"ListDashboards":   {},
		"DeleteDashboards": {"DashboardNames": []any{auditDoomedDashboard}},
		"TagResource": {
			"ResourceARN": awsident.ARN("cloudwatch", "alarm:"+auditAlarm),
			"Tags":        []any{map[string]any{"Key": "team", "Value": "audit"}},
		},
		"UntagResource": {
			"ResourceARN": awsident.ARN("cloudwatch", "alarm:"+auditAlarm),
			"TagKeys":     []any{"team"},
		},
		"ListTagsForResource": {
			"ResourceARN": awsident.ARN("cloudwatch", "alarm:"+auditAlarm),
		},
	}
}

// The fixture's named resources. The doomed pair exist so the two destructive
// operations have something of their own to consume.
const (
	auditAlarm           = "audit-alarm"
	auditDoomedAlarm     = "audit-doomed-alarm"
	auditDashboard       = "audit-dashboard"
	auditDoomedDashboard = "audit-doomed-dashboard"
)

// exemplars are valid fillers for the containers a case reaches through. A
// constraint on Dimensions[].Name can only be tested if the Dimensions list
// itself is acceptable; without this a case would be refused for the
// container and read as enforcement of the leaf.
// A key ending in [] names a LIST container, so its exemplar is a list —
// Apply assigns the exemplar and then walks the marker into it, and a bare
// element would fail as "not a non-empty list". Only the containers a
// baseline already carries hide that distinction, which is why the two it
// does not carry — ListMetrics's Dimensions and PutMetricData's
// EntityMetricData — were the ones that caught it.
func exemplars() map[string]any {
	metricStat := map[string]any{
		"Metric": map[string]any{"Namespace": "Audit", "MetricName": "Probe"},
		"Period": 60.0, "Stat": "Sum",
	}
	dimension := map[string]any{"Name": "Stage", "Value": "prod"}
	datum := map[string]any{"MetricName": "Probe", "Value": 1.0}
	return map[string]any{
		"MetricData[]":                    []any{datum},
		"MetricData[].Dimensions[]":       []any{dimension},
		"MetricData[].StatisticValues":    map[string]any{"SampleCount": 1.0, "Sum": 1.0, "Minimum": 1.0, "Maximum": 1.0},
		"Dimensions[]":                    []any{dimension},
		"Statistics[]":                    []any{"Sum"},
		"ExtendedStatistics[]":            []any{"p99"},
		"MetricDataQueries[]":             []any{map[string]any{"Id": "q1", "MetricStat": metricStat}},
		"MetricDataQueries[].MetricStat":  metricStat,
		"EntityMetricData[]":              []any{map[string]any{"MetricData": []any{datum}}},
		"EntityMetricData[].MetricData[]": []any{datum},
		"Tags[]":                          []any{map[string]any{"Key": "team", "Value": "audit"}},
	}
}

// outOfScope are the case paths that reach INTO a feature doze-aws refuses
// wholesale. Replaying one would be the exact trap this suite exists to
// avoid, in its most convincing form: the request IS refused, so the runner
// records the constraint as enforced — but it was refused for the feature,
// not for the value, and the constraint is not checked at all.
//
// Each entry is a path prefix and why the feature is not here. The refusal
// itself is tested where it belongs, by name, in the alarm tests.
var outOfScope = map[string]string{
	"Metrics": "metric math: PutMetricAlarm refuses Metrics by name, so every " +
		"case under it would be refused for the feature rather than the value",
	"WarmUpConfiguration": "alarm warm-up: refused by name, same reason",
}

// skipReason answers why a case is out of scope, or "" when it should run.
func skipReason(path string) string {
	for prefix, why := range outOfScope {
		if path == prefix || strings.HasPrefix(path, prefix+".") || strings.HasPrefix(path, prefix+"[") {
			return why
		}
	}
	return ""
}

// knownGaps are constraints doze-aws does not yet enforce, listed explicitly
// so the number can only go down. An empty map is the goal; an entry that
// starts passing fails the test as a stale excuse.
var knownGaps = map[string]bool{}

// wires is the three protocols, each with a way to send one request.
var wires = []struct {
	name string
	send func(t *testing.T, base, op string, body map[string]any) (int, []byte)
}{
	{"awsJson1_0", sendJSON},
	{"rpcv2Cbor", sendCBOR},
	{"awsQuery", sendQuery},
}

func sendJSON(t *testing.T, base, op string, body map[string]any) (int, []byte) {
	t.Helper()
	raw, err := json.Marshal(body)
	if err != nil {
		t.Fatal(err)
	}
	code, _, out := do(t, jsonRequest(t, base, op, string(raw)))
	return code, out
}

func sendCBOR(t *testing.T, base, op string, body map[string]any) (int, []byte) {
	t.Helper()
	raw, err := rpcv2cbor.Marshal(body)
	if err != nil {
		t.Fatal(err)
	}
	code, _, out := do(t, rawCBOR(t, base, op, raw))
	return code, out
}

// sendQuery flattens a body the way an SDK would, which is also the only way
// to reach the Query lane's un-flattener with a nested shape.
func sendQuery(t *testing.T, base, op string, body map[string]any) (int, []byte) {
	t.Helper()
	form := []string{"Action=" + op, "Version=2010-08-01"}
	for k, v := range body {
		form = append(form, flatten(k, v)...)
	}
	code, _, out := do(t, queryRequest(t, base, strings.Join(form, "&")))
	return code, out
}

// flatten renders one member as Query parameters.
func flatten(prefix string, v any) []string {
	switch t := v.(type) {
	case map[string]any:
		var out []string
		for k, sub := range t {
			out = append(out, flatten(prefix+"."+k, sub)...)
		}
		return out
	case []any:
		var out []string
		for i, el := range t {
			out = append(out, flatten(fmt.Sprintf("%s.member.%d", prefix, i+1), el)...)
		}
		return out
	case nil:
		return nil
	case string:
		return []string{prefix + "=" + urlEscape(t)}
	case bool:
		return []string{fmt.Sprintf("%s=%t", prefix, t)}
	case float64:
		return []string{prefix + "=" + strconvFloat(t)}
	}
	return []string{fmt.Sprintf("%s=%v", prefix, v)}
}

func strconvFloat(f float64) string {
	if f == float64(int64(f)) {
		return fmt.Sprintf("%d", int64(f))
	}
	return fmt.Sprintf("%g", f)
}

func urlEscape(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9',
			c == '-', c == '_', c == '.', c == '~':
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, "%%%02X", c)
		}
	}
	return b.String()
}

func TestCloudWatchRejectsWhatTheModelForbids(t *testing.T) {
	if testing.Short() {
		t.Skip("boots a store")
	}
	ts := server(t)
	// One series so the read operations have something real to address.
	seedAudit(t, ts.URL)

	cases := loadCases(t)
	base := baselines()
	ex := exemplars()

	for _, w := range wires {
		t.Run(w.name, func(t *testing.T) {
			// The previous wire's baseline pass consumed the doomed alarm and
			// dashboard; put them back before this one runs.
			seedAudit(t, ts.URL)
			// Every baseline must be accepted before any mutation of it means
			// anything. A failure here is unusable, not a pass.
			for op, body := range base {
				code, out := w.send(t, ts.URL, op, auditkit.DeepCopy(body).(map[string]any))
				if code != 200 {
					t.Fatalf("the %s baseline is not accepted (%d): %s\n"+
						"every case for it would be refused for the baseline, not the mutation",
						op, code, truncate(out))
				}
			}

			checked, gaps, skipped := 0, 0, 0
			for _, c := range cases {
				if skipReason(c.Path) != "" {
					skipped++
					continue
				}
				body := auditkit.DeepCopy(base[c.Operation]).(map[string]any)
				if err := auditkit.Apply(body, ex, c.Path, c.Value, true); err != nil {
					t.Errorf("%s %s: building the case: %v", c.Operation, c.Path, err)
					continue
				}
				code, out := w.send(t, ts.URL, c.Operation, body)
				key := c.Operation + " " + c.Path + " " + c.Why
				switch {
				case code >= 500:
					// A refusal must be well-formed, not panic-shaped.
					t.Errorf("%s: %d — a refusal must be a 4xx, not a server error: %s",
						key, code, truncate(out))
				case code == 200:
					if knownGaps[key] {
						gaps++
						continue
					}
					t.Errorf("%s (%s) was ACCEPTED", key, c.Constraint)
				default:
					if knownGaps[key] {
						t.Errorf("%s is listed in knownGaps but is now enforced — "+
							"remove the entry", key)
					}
					checked++
				}
			}
			t.Logf("%s: %d/%d model constraints enforced across %d dispatched operations "+
				"(%d out of scope)", w.name, checked, len(cases)-skipped, len(base), skipped)
			if gaps > len(knownGaps) {
				t.Errorf("%d unlisted gaps", gaps-len(knownGaps))
			}
		})
	}
}

// seedAudit puts the fixture in place: one series, the alarms and the
// dashboards the baselines address.
//
// Called once per wire rather than once per test, because the baseline pass
// runs every baseline — including DeleteAlarms and DeleteDashboards, which
// consume what they name. Without a re-seed the second wire's baseline pass
// would fail on a resource the first wire deleted, and the failure would look
// like a protocol bug rather than a fixture one.
func seedAudit(t *testing.T, base string) {
	t.Helper()
	post := func(op, body string) {
		t.Helper()
		if code, _, out := do(t, jsonRequest(t, base, op, body)); code != 200 {
			t.Fatalf("seeding %s: %d: %s", op, code, out)
		}
	}
	post("PutMetricData", `{"Namespace":"Audit","MetricData":[{"MetricName":"Probe","Value":1,`+
		`"Unit":"Count","Dimensions":[{"Name":"Stage","Value":"prod"}],`+
		`"Timestamp":"2026-09-10T11:30:00Z"}]}`)
	for _, name := range []string{auditAlarm, auditDoomedAlarm} {
		post("PutMetricAlarm", `{"AlarmName":"`+name+`","Namespace":"Audit","MetricName":"Probe",`+
			`"Statistic":"Sum","Period":60,"EvaluationPeriods":1,`+
			`"ComparisonOperator":"GreaterThanThreshold","Threshold":1,`+
			`"Dimensions":[{"Name":"Stage","Value":"prod"}]}`)
	}
	for _, name := range []string{auditDashboard, auditDoomedDashboard} {
		post("PutDashboard", `{"DashboardName":"`+name+`","DashboardBody":"{\"widgets\":[]}"}`)
	}
	// TagResource's baseline adds this tag; UntagResource's removes it. The
	// order the two baselines run in is map order, so the tag is seeded here
	// and neither baseline depends on the other having gone first.
	post("TagResource", `{"ResourceARN":"`+awsident.ARN("cloudwatch", "alarm:"+auditAlarm)+`",`+
		`"Tags":[{"Key":"team","Value":"audit"}]}`)
}

func truncate(b []byte) string {
	const max = 300
	if len(b) <= max {
		return string(b)
	}
	return string(b[:max]) + "…"
}
