package cloudwatch_test

// Rejection parity: does doze-aws refuse what CloudWatch refuses?
//
// The cases are generated by `dzaudit cases cloudwatch` from AWS's own service
// model and committed to testdata/, so the checklist is not something anyone
// remembered to write. Each case names one constrained input and a value that
// violates it.
//
// # The trap this is built around
//
// A request refused for the WRONG reason looks exactly like a pass. Send a
// PutMetricData with a bad Unit and no Namespace and it is refused — for the
// missing namespace — and a runner that only asks "was it refused" records a
// validation that does not exist. So every case is a mutation OF a baseline
// the test first proves the service ACCEPTS. A baseline that fails is
// reported as unusable, not as a pass.
//
// # Three wires, one fixture
//
// Every case is replayed over all three protocols. The constraint table is
// written once against the JSON shape, and CBOR and Query are normalised into
// it, so a case that refuses on one wire and not another means the
// normalisation is lying — which is exactly the class of bug that made the
// Query lane drop list elements. Nothing else here has three chances to be
// wrong, so nothing else gets this treatment.

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/doze-dev/doze-aws/internal/auditkit"
	"github.com/doze-dev/doze-aws/internal/rpcv2cbor"
)

type auditCase struct {
	Operation   string           `json:"operation"`
	Target      string           `json:"target"`
	Path        string           `json:"path"`
	Why         string           `json:"why"`
	Value       any              `json:"value"`
	ValueRepeat *auditkit.Repeat `json:"value_repeat,omitempty"`
	Constraint  string           `json:"constraint"`
}

// dispatched is the set of operations with a real handler. A case against a
// refused operation proves nothing — it answers UnsupportedOperationException
// whatever the input — so replaying one would be a case that cannot fail.
var dispatched = map[string]bool{
	"PutMetricData": true, "ListMetrics": true,
	"GetMetricStatistics": true, "GetMetricData": true,
}

func loadCases(t *testing.T) []auditCase {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "cases_cloudwatch.json"))
	if err != nil {
		t.Fatal(err)
	}
	var all []auditCase
	if err := json.Unmarshal(raw, &all); err != nil {
		t.Fatal(err)
	}
	var cs []auditCase
	for _, c := range all {
		// A max-length case stores the shape of its padding, not the run.
		c.Value = auditkit.Materialize(c.Value, c.ValueRepeat)
		if dispatched[c.Operation] {
			cs = append(cs, c)
		}
	}
	if len(cs) == 0 {
		t.Fatal("no cases: the audit would pass vacuously")
	}
	return cs
}

// baselines is one request per dispatched operation that the service is
// expected to accept. Everything below is a mutation of one of these.
func baselines() map[string]map[string]any {
	from := "2026-09-10T11:00:00Z"
	to := "2026-09-10T12:00:00Z"
	return map[string]map[string]any{
		"PutMetricData": {
			"Namespace": "Audit",
			"MetricData": []any{map[string]any{
				"MetricName": "Probe",
				"Value":      1.0,
				"Unit":       "Count",
				"Dimensions": []any{map[string]any{"Name": "Stage", "Value": "prod"}},
			}},
		},
		"ListMetrics": {
			"Namespace": "Audit",
		},
		"GetMetricStatistics": {
			"Namespace": "Audit", "MetricName": "Probe",
			"StartTime": from, "EndTime": to,
			"Period":     60.0,
			"Statistics": []any{"Sum"},
			"Dimensions": []any{map[string]any{"Name": "Stage", "Value": "prod"}},
		},
		"GetMetricData": {
			"StartTime": from, "EndTime": to,
			"MetricDataQueries": []any{map[string]any{
				"Id": "q1",
				"MetricStat": map[string]any{
					"Metric": map[string]any{"Namespace": "Audit", "MetricName": "Probe"},
					"Period": 60.0,
					"Stat":   "Sum",
				},
			}},
		},
	}
}

// exemplars are valid fillers for the containers a case reaches through. A
// constraint on Dimensions[].Name can only be tested if the Dimensions list
// itself is acceptable; without this a case would be refused for the
// container and read as enforcement of the leaf.
// A key ending in [] names a LIST container, so its exemplar is a list —
// Apply assigns the exemplar and then walks the marker into it, and a bare
// element would fail as "not a non-empty list". Only the containers a
// baseline already carries hide that distinction, which is why the two it
// does not carry — ListMetrics's Dimensions and PutMetricData's
// EntityMetricData — were the ones that caught it.
func exemplars() map[string]any {
	metricStat := map[string]any{
		"Metric": map[string]any{"Namespace": "Audit", "MetricName": "Probe"},
		"Period": 60.0, "Stat": "Sum",
	}
	dimension := map[string]any{"Name": "Stage", "Value": "prod"}
	datum := map[string]any{"MetricName": "Probe", "Value": 1.0}
	return map[string]any{
		"MetricData[]":                    []any{datum},
		"MetricData[].Dimensions[]":       []any{dimension},
		"MetricData[].StatisticValues":    map[string]any{"SampleCount": 1.0, "Sum": 1.0, "Minimum": 1.0, "Maximum": 1.0},
		"Dimensions[]":                    []any{dimension},
		"Statistics[]":                    []any{"Sum"},
		"ExtendedStatistics[]":            []any{"p99"},
		"MetricDataQueries[]":             []any{map[string]any{"Id": "q1", "MetricStat": metricStat}},
		"MetricDataQueries[].MetricStat":  metricStat,
		"EntityMetricData[]":              []any{map[string]any{"MetricData": []any{datum}}},
		"EntityMetricData[].MetricData[]": []any{datum},
	}
}

// knownGaps are constraints doze-aws does not yet enforce, listed explicitly
// so the number can only go down. An empty map is the goal; an entry that
// starts passing fails the test as a stale excuse.
var knownGaps = map[string]bool{}

// wires is the three protocols, each with a way to send one request.
var wires = []struct {
	name string
	send func(t *testing.T, base, op string, body map[string]any) (int, []byte)
}{
	{"awsJson1_0", sendJSON},
	{"rpcv2Cbor", sendCBOR},
	{"awsQuery", sendQuery},
}

func sendJSON(t *testing.T, base, op string, body map[string]any) (int, []byte) {
	t.Helper()
	raw, err := json.Marshal(body)
	if err != nil {
		t.Fatal(err)
	}
	code, _, out := do(t, jsonRequest(t, base, op, string(raw)))
	return code, out
}

func sendCBOR(t *testing.T, base, op string, body map[string]any) (int, []byte) {
	t.Helper()
	raw, err := rpcv2cbor.Marshal(body)
	if err != nil {
		t.Fatal(err)
	}
	code, _, out := do(t, rawCBOR(t, base, op, raw))
	return code, out
}

// sendQuery flattens a body the way an SDK would, which is also the only way
// to reach the Query lane's un-flattener with a nested shape.
func sendQuery(t *testing.T, base, op string, body map[string]any) (int, []byte) {
	t.Helper()
	form := []string{"Action=" + op, "Version=2010-08-01"}
	for k, v := range body {
		form = append(form, flatten(k, v)...)
	}
	code, _, out := do(t, queryRequest(t, base, strings.Join(form, "&")))
	return code, out
}

// flatten renders one member as Query parameters.
func flatten(prefix string, v any) []string {
	switch t := v.(type) {
	case map[string]any:
		var out []string
		for k, sub := range t {
			out = append(out, flatten(prefix+"."+k, sub)...)
		}
		return out
	case []any:
		var out []string
		for i, el := range t {
			out = append(out, flatten(fmt.Sprintf("%s.member.%d", prefix, i+1), el)...)
		}
		return out
	case nil:
		return nil
	case string:
		return []string{prefix + "=" + urlEscape(t)}
	case bool:
		return []string{fmt.Sprintf("%s=%t", prefix, t)}
	case float64:
		return []string{prefix + "=" + strconvFloat(t)}
	}
	return []string{fmt.Sprintf("%s=%v", prefix, v)}
}

func strconvFloat(f float64) string {
	if f == float64(int64(f)) {
		return fmt.Sprintf("%d", int64(f))
	}
	return fmt.Sprintf("%g", f)
}

func urlEscape(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9',
			c == '-', c == '_', c == '.', c == '~':
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, "%%%02X", c)
		}
	}
	return b.String()
}

func TestCloudWatchRejectsWhatTheModelForbids(t *testing.T) {
	if testing.Short() {
		t.Skip("boots a store")
	}
	ts := server(t)
	// One series so the read operations have something real to address.
	seedAudit(t, ts.URL)

	cases := loadCases(t)
	base := baselines()
	ex := exemplars()

	for _, w := range wires {
		t.Run(w.name, func(t *testing.T) {
			// Every baseline must be accepted before any mutation of it means
			// anything. A failure here is unusable, not a pass.
			for op, body := range base {
				code, out := w.send(t, ts.URL, op, auditkit.DeepCopy(body).(map[string]any))
				if code != 200 {
					t.Fatalf("the %s baseline is not accepted (%d): %s\n"+
						"every case for it would be refused for the baseline, not the mutation",
						op, code, truncate(out))
				}
			}

			checked, gaps := 0, 0
			for _, c := range cases {
				body := auditkit.DeepCopy(base[c.Operation]).(map[string]any)
				if err := auditkit.Apply(body, ex, c.Path, c.Value, true); err != nil {
					t.Errorf("%s %s: building the case: %v", c.Operation, c.Path, err)
					continue
				}
				code, out := w.send(t, ts.URL, c.Operation, body)
				key := c.Operation + " " + c.Path + " " + c.Why
				switch {
				case code >= 500:
					// A refusal must be well-formed, not panic-shaped.
					t.Errorf("%s: %d — a refusal must be a 4xx, not a server error: %s",
						key, code, truncate(out))
				case code == 200:
					if knownGaps[key] {
						gaps++
						continue
					}
					t.Errorf("%s (%s) was ACCEPTED", key, c.Constraint)
				default:
					if knownGaps[key] {
						t.Errorf("%s is listed in knownGaps but is now enforced — "+
							"remove the entry", key)
					}
					checked++
				}
			}
			t.Logf("%s: %d/%d model constraints enforced across %d dispatched operations",
				w.name, checked, len(cases), len(base))
			if gaps > len(knownGaps) {
				t.Errorf("%d unlisted gaps", gaps-len(knownGaps))
			}
		})
	}
}

// seedAudit publishes the series the read baselines address, so a baseline is
// accepted for the right reason rather than by answering an empty result.
func seedAudit(t *testing.T, base string) {
	t.Helper()
	body := `{"Namespace":"Audit","MetricData":[{"MetricName":"Probe","Value":1,` +
		`"Unit":"Count","Dimensions":[{"Name":"Stage","Value":"prod"}],` +
		`"Timestamp":"2026-09-10T11:30:00Z"}]}`
	if code, _, out := do(t, jsonRequest(t, base, "PutMetricData", body)); code != 200 {
		t.Fatalf("seeding: %d: %s", code, out)
	}
}

func truncate(b []byte) string {
	const max = 300
	if len(b) <= max {
		return string(b)
	}
	return string(b[:max]) + "…"
}
