package s3

// The model-derived constraint tables, keyed by operation. Generated with
// `dzaudit cases s3` and replayed by rejection_parity_test.go; kept apart
// from the route table so each file stays readable.

import (
	"github.com/doze-dev/doze-aws/internal/modelcheck"
)

var constraintTables = map[string][]modelcheck.Constraint{
	"AbortMultipartUpload": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
		{Path: "UploadId", Kind: modelcheck.KindRequired},
	},
	"CompleteMultipartUpload": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumType", Kind: modelcheck.KindEnum, Enum: []string{"COMPOSITE", "FULL_OBJECT"}},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
		{Path: "UploadId", Kind: modelcheck.KindRequired},
	},
	"CopyObject": {
		{Path: "ACL", Kind: modelcheck.KindEnum, Enum: []string{"public-read-write", "authenticated-read", "aws-exec-read", "bucket-owner-read", "bucket-owner-full-control", "private", "public-read"}},
		{Path: "AnnotationDirective", Kind: modelcheck.KindEnum, Enum: []string{"COPY", "EXCLUDE"}},
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"XXHASH128", "CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5", "SHA256", "XXHASH64", "XXHASH3"}},
		{Path: "CopySource", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^\/?.+\/.+$`)},
		{Path: "CopySource", Kind: modelcheck.KindRequired},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "MetadataDirective", Kind: modelcheck.KindEnum, Enum: []string{"COPY", "REPLACE"}},
		{Path: "ObjectLockLegalHoldStatus", Kind: modelcheck.KindEnum, Enum: []string{"ON", "OFF"}},
		{Path: "ObjectLockMode", Kind: modelcheck.KindEnum, Enum: []string{"GOVERNANCE", "COMPLIANCE"}},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
		{Path: "ServerSideEncryption", Kind: modelcheck.KindEnum, Enum: []string{"AES256", "aws:fsx", "aws:backup", "aws:kms", "aws:kms:dsse"}},
		{Path: "StorageClass", Kind: modelcheck.KindEnum, Enum: []string{"GLACIER", "GLACIER_IR", "ONEZONE_IA", "INTELLIGENT_TIERING", "AWS_BACKUP_LOW_COST_WARM", "STANDARD_IA", "DEEP_ARCHIVE", "OUTPOSTS", "EXPRESS_ONEZONE", "FSX_ONTAP", "AWS_BACKUP_WARM", "STANDARD", "SNOW", "FSX_OPENZFS", "REDUCED_REDUNDANCY"}},
		{Path: "TaggingDirective", Kind: modelcheck.KindEnum, Enum: []string{"REPLACE", "COPY"}},
	},
	"CreateBucket": {
		{Path: "ACL", Kind: modelcheck.KindEnum, Enum: []string{"private", "public-read", "public-read-write", "authenticated-read"}},
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "BucketNamespace", Kind: modelcheck.KindEnum, Enum: []string{"account-regional", "global"}},
		{Path: "CreateBucketConfiguration.Bucket.DataRedundancy", Kind: modelcheck.KindEnum, Enum: []string{"SingleLocalZone", "SingleAvailabilityZone"}},
		{Path: "CreateBucketConfiguration.Bucket.Type", Kind: modelcheck.KindEnum, Enum: []string{"Directory"}},
		{Path: "CreateBucketConfiguration.Location.Type", Kind: modelcheck.KindEnum, Enum: []string{"AvailabilityZone", "LocalZone"}},
		{Path: "CreateBucketConfiguration.LocationConstraint", Kind: modelcheck.KindEnum, Enum: []string{"af-south-1", "ap-northeast-3", "ap-southeast-2", "mx-central-1", "us-west-1", "us-west-2", "ap-south-1", "ca-central-1", "eu-central-1", "ap-northeast-2", "ap-southeast-5", "eu-west-3", "me-central-1", "ap-southeast-4", "ap-southeast-6", "eu-central-2", "eu-south-2", "il-central-1", "us-gov-west-1", "ap-east-1", "ap-northeast-1", "eu-west-1", "eu-west-2", "me-south-1", "us-east-2", "us-gov-east-1", "ap-south-2", "cn-north-1", "eu-north-1", "ap-southeast-1", "cn-northwest-1", "ap-east-2", "ap-southeast-3", "ap-southeast-7", "ca-west-1", "EU", "eu-south-1", "sa-east-1"}},
		{Path: "CreateBucketConfiguration.Tags[].Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "CreateBucketConfiguration.Tags[].Key", Kind: modelcheck.KindRequired},
		{Path: "CreateBucketConfiguration.Tags[].Value", Kind: modelcheck.KindRequired},
		{Path: "ObjectOwnership", Kind: modelcheck.KindEnum, Enum: []string{"BucketOwnerPreferred", "ObjectWriter", "BucketOwnerEnforced"}},
	},
	"CreateMultipartUpload": {
		{Path: "ACL", Kind: modelcheck.KindEnum, Enum: []string{"authenticated-read", "aws-exec-read", "bucket-owner-read", "bucket-owner-full-control", "private", "public-read", "public-read-write"}},
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5", "SHA256", "XXHASH64", "XXHASH3", "XXHASH128"}},
		{Path: "ChecksumType", Kind: modelcheck.KindEnum, Enum: []string{"COMPOSITE", "FULL_OBJECT"}},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "ObjectLockLegalHoldStatus", Kind: modelcheck.KindEnum, Enum: []string{"ON", "OFF"}},
		{Path: "ObjectLockMode", Kind: modelcheck.KindEnum, Enum: []string{"GOVERNANCE", "COMPLIANCE"}},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
		{Path: "ServerSideEncryption", Kind: modelcheck.KindEnum, Enum: []string{"AES256", "aws:fsx", "aws:backup", "aws:kms", "aws:kms:dsse"}},
		{Path: "StorageClass", Kind: modelcheck.KindEnum, Enum: []string{"INTELLIGENT_TIERING", "AWS_BACKUP_LOW_COST_WARM", "STANDARD_IA", "DEEP_ARCHIVE", "OUTPOSTS", "EXPRESS_ONEZONE", "FSX_ONTAP", "AWS_BACKUP_WARM", "STANDARD", "SNOW", "FSX_OPENZFS", "REDUCED_REDUNDANCY", "GLACIER", "GLACIER_IR", "ONEZONE_IA"}},
	},
	"DeleteBucket": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"DeleteBucketCors": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"DeleteBucketLifecycle": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"DeleteBucketPolicy": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"DeleteBucketReplication": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"DeleteBucketTagging": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"DeleteBucketWebsite": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"DeleteObject": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
	},
	"DeleteObjectTagging": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
	},
	"DeleteObjects": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"SHA1", "CRC64NVME", "SHA512", "MD5", "SHA256", "XXHASH64", "XXHASH3", "XXHASH128", "CRC32", "CRC32C"}},
		{Path: "Delete", Kind: modelcheck.KindRequired},
		{Path: "Delete.Objects", Kind: modelcheck.KindRequired},
		{Path: "Delete.Objects[].Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Delete.Objects[].Key", Kind: modelcheck.KindRequired},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
	},
	"GetBucketAccelerateConfiguration": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
	},
	"GetBucketAcl": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"GetBucketCors": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"GetBucketLifecycleConfiguration": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"GetBucketLocation": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"GetBucketLogging": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"GetBucketNotificationConfiguration": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"GetBucketPolicy": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"GetBucketReplication": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"GetBucketRequestPayment": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"GetBucketTagging": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"GetBucketVersioning": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"GetBucketWebsite": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"GetObject": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumMode", Kind: modelcheck.KindEnum, Enum: []string{"ENABLED"}},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
	},
	"GetObjectAcl": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
	},
	"GetObjectAttributes": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "ObjectAttributes", Kind: modelcheck.KindRequired},
		{Path: "ObjectAttributes[]", Kind: modelcheck.KindEnum, Enum: []string{"ETag", "Checksum", "ObjectParts", "StorageClass", "ObjectSize"}},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
	},
	"GetObjectLegalHold": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
	},
	"GetObjectLockConfiguration": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"GetObjectRetention": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
	},
	"GetObjectTagging": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
	},
	"HeadBucket": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
	},
	"HeadObject": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumMode", Kind: modelcheck.KindEnum, Enum: []string{"ENABLED"}},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
	},
	"ListBuckets": {
		{Path: "MaxBuckets", Kind: modelcheck.KindRange, Min: 1, Max: 10000},
	},
	"ListDirectoryBuckets": {
		{Path: "ContinuationToken", Kind: modelcheck.KindLength, Min: 0, Max: 1024},
		{Path: "MaxDirectoryBuckets", Kind: modelcheck.KindRange, Min: 0, Max: 1000},
	},
	"ListMultipartUploads": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "EncodingType", Kind: modelcheck.KindEnum, Enum: []string{"url"}},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
	},
	"ListObjectVersions": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "EncodingType", Kind: modelcheck.KindEnum, Enum: []string{"url"}},
		{Path: "OptionalObjectAttributes[]", Kind: modelcheck.KindEnum, Enum: []string{"RestoreStatus"}},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
	},
	"ListObjects": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "EncodingType", Kind: modelcheck.KindEnum, Enum: []string{"url"}},
		{Path: "OptionalObjectAttributes[]", Kind: modelcheck.KindEnum, Enum: []string{"RestoreStatus"}},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
	},
	"ListObjectsV2": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "EncodingType", Kind: modelcheck.KindEnum, Enum: []string{"url"}},
		{Path: "OptionalObjectAttributes[]", Kind: modelcheck.KindEnum, Enum: []string{"RestoreStatus"}},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
	},
	"ListParts": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
		{Path: "UploadId", Kind: modelcheck.KindRequired},
	},
	"PutBucketAccelerateConfiguration": {
		{Path: "AccelerateConfiguration", Kind: modelcheck.KindRequired},
		{Path: "AccelerateConfiguration.Status", Kind: modelcheck.KindEnum, Enum: []string{"Enabled", "Suspended"}},
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5", "SHA256", "XXHASH64", "XXHASH3", "XXHASH128", "CRC32"}},
	},
	"PutBucketAcl": {
		{Path: "ACL", Kind: modelcheck.KindEnum, Enum: []string{"private", "public-read", "public-read-write", "authenticated-read"}},
		{Path: "AccessControlPolicy.Grants[].Grantee.Type", Kind: modelcheck.KindRequired},
		{Path: "AccessControlPolicy.Grants[].Permission", Kind: modelcheck.KindEnum, Enum: []string{"WRITE", "WRITE_ACP", "READ", "READ_ACP", "FULL_CONTROL"}},
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5", "SHA256", "XXHASH64", "XXHASH3", "XXHASH128"}},
	},
	"PutBucketCors": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "CORSConfiguration", Kind: modelcheck.KindRequired},
		{Path: "CORSConfiguration.CORSRules", Kind: modelcheck.KindRequired},
		{Path: "CORSConfiguration.CORSRules[].AllowedMethods", Kind: modelcheck.KindRequired},
		{Path: "CORSConfiguration.CORSRules[].AllowedOrigins", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5", "SHA256", "XXHASH64", "XXHASH3", "XXHASH128"}},
	},
	"PutBucketLifecycleConfiguration": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5", "SHA256", "XXHASH64", "XXHASH3", "XXHASH128"}},
		{Path: "LifecycleConfiguration.Rules", Kind: modelcheck.KindRequired},
		{Path: "LifecycleConfiguration.Rules[].Status", Kind: modelcheck.KindEnum, Enum: []string{"Enabled", "Disabled"}},
		{Path: "LifecycleConfiguration.Rules[].Status", Kind: modelcheck.KindRequired},
		{Path: "TransitionDefaultMinimumObjectSize", Kind: modelcheck.KindEnum, Enum: []string{"all_storage_classes_128K", "varies_by_storage_class"}},
	},
	"PutBucketLogging": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "BucketLoggingStatus", Kind: modelcheck.KindRequired},
		{Path: "BucketLoggingStatus.LoggingEnabled.TargetBucket", Kind: modelcheck.KindRequired},
		{Path: "BucketLoggingStatus.LoggingEnabled.TargetPrefix", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5", "SHA256", "XXHASH64", "XXHASH3", "XXHASH128"}},
	},
	"PutBucketNotificationConfiguration": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "NotificationConfiguration", Kind: modelcheck.KindRequired},
		{Path: "NotificationConfiguration.LambdaFunctionConfigurations[].Events", Kind: modelcheck.KindRequired},
		{Path: "NotificationConfiguration.LambdaFunctionConfigurations[].LambdaFunctionArn", Kind: modelcheck.KindRequired},
		{Path: "NotificationConfiguration.QueueConfigurations[].Events", Kind: modelcheck.KindRequired},
		{Path: "NotificationConfiguration.QueueConfigurations[].QueueArn", Kind: modelcheck.KindRequired},
		{Path: "NotificationConfiguration.TopicConfigurations[].Events", Kind: modelcheck.KindRequired},
		{Path: "NotificationConfiguration.TopicConfigurations[].TopicArn", Kind: modelcheck.KindRequired},
	},
	"PutBucketPolicy": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"SHA256", "XXHASH64", "XXHASH3", "XXHASH128", "CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5"}},
		{Path: "Policy", Kind: modelcheck.KindRequired},
	},
	"DeleteBucketEncryption":        {{Path: "Bucket", Kind: modelcheck.KindRequired}},
	"DeleteBucketOwnershipControls": {{Path: "Bucket", Kind: modelcheck.KindRequired}},
	"DeletePublicAccessBlock":       {{Path: "Bucket", Kind: modelcheck.KindRequired}},
	"GetBucketEncryption":           {{Path: "Bucket", Kind: modelcheck.KindRequired}},
	"GetBucketOwnershipControls":    {{Path: "Bucket", Kind: modelcheck.KindRequired}},
	"GetBucketPolicyStatus":         {{Path: "Bucket", Kind: modelcheck.KindRequired}},
	"GetPublicAccessBlock":          {{Path: "Bucket", Kind: modelcheck.KindRequired}},
	"PutBucketEncryption": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"SHA256", "XXHASH64", "XXHASH3", "XXHASH128", "CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5"}},
		{Path: "ServerSideEncryptionConfiguration", Kind: modelcheck.KindRequired},
		{Path: "ServerSideEncryptionConfiguration.Rules", Kind: modelcheck.KindRequired},
		{Path: "ServerSideEncryptionConfiguration.Rules[].ApplyServerSideEncryptionByDefault.SSEAlgorithm", Kind: modelcheck.KindRequired},
	},
	"PutBucketOwnershipControls": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"SHA256", "XXHASH64", "XXHASH3", "XXHASH128", "CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5"}},
		{Path: "OwnershipControls", Kind: modelcheck.KindRequired},
		{Path: "OwnershipControls.Rules", Kind: modelcheck.KindRequired},
		{Path: "OwnershipControls.Rules[].ObjectOwnership", Kind: modelcheck.KindRequired},
		{Path: "OwnershipControls.Rules[].ObjectOwnership", Kind: modelcheck.KindEnum, Enum: []string{"BucketOwnerPreferred", "ObjectWriter", "BucketOwnerEnforced"}},
	},
	"PutPublicAccessBlock": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"SHA256", "XXHASH64", "XXHASH3", "XXHASH128", "CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5"}},
		{Path: "PublicAccessBlockConfiguration", Kind: modelcheck.KindRequired},
	},
	"PutBucketReplication": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"XXHASH3", "XXHASH128", "CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5", "SHA256", "XXHASH64"}},
		{Path: "ReplicationConfiguration", Kind: modelcheck.KindRequired},
		{Path: "ReplicationConfiguration.Role", Kind: modelcheck.KindRequired},
		{Path: "ReplicationConfiguration.Rules", Kind: modelcheck.KindRequired},
		{Path: "ReplicationConfiguration.Rules[].Destination", Kind: modelcheck.KindRequired},
		{Path: "ReplicationConfiguration.Rules[].Destination.Bucket", Kind: modelcheck.KindRequired},
		{Path: "ReplicationConfiguration.Rules[].ExistingObjectReplication.Status", Kind: modelcheck.KindRequired},
		{Path: "ReplicationConfiguration.Rules[].Status", Kind: modelcheck.KindEnum, Enum: []string{"Enabled", "Disabled"}},
		{Path: "ReplicationConfiguration.Rules[].Status", Kind: modelcheck.KindRequired},
	},
	"PutBucketRequestPayment": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"XXHASH3", "XXHASH128", "CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5", "SHA256", "XXHASH64"}},
		{Path: "RequestPaymentConfiguration", Kind: modelcheck.KindRequired},
		{Path: "RequestPaymentConfiguration.Payer", Kind: modelcheck.KindEnum, Enum: []string{"Requester", "BucketOwner"}},
		{Path: "RequestPaymentConfiguration.Payer", Kind: modelcheck.KindRequired},
	},
	"PutBucketTagging": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"SHA256", "XXHASH64", "XXHASH3", "XXHASH128", "CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5"}},
		{Path: "Tagging", Kind: modelcheck.KindRequired},
		{Path: "Tagging.TagSet", Kind: modelcheck.KindRequired},
		{Path: "Tagging.TagSet[].Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Tagging.TagSet[].Key", Kind: modelcheck.KindRequired},
		{Path: "Tagging.TagSet[].Value", Kind: modelcheck.KindRequired},
	},
	"PutBucketVersioning": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"SHA1", "CRC64NVME", "SHA512", "MD5", "SHA256", "XXHASH64", "XXHASH3", "XXHASH128", "CRC32", "CRC32C"}},
		{Path: "VersioningConfiguration", Kind: modelcheck.KindRequired},
		{Path: "VersioningConfiguration.MFADelete", Kind: modelcheck.KindEnum, Enum: []string{"Enabled", "Disabled"}},
		{Path: "VersioningConfiguration.Status", Kind: modelcheck.KindEnum, Enum: []string{"Enabled", "Suspended"}},
	},
	"PutBucketWebsite": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"XXHASH128", "CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5", "SHA256", "XXHASH64", "XXHASH3"}},
		{Path: "WebsiteConfiguration", Kind: modelcheck.KindRequired},
		{Path: "WebsiteConfiguration.ErrorDocument.Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "WebsiteConfiguration.ErrorDocument.Key", Kind: modelcheck.KindRequired},
		{Path: "WebsiteConfiguration.IndexDocument.Suffix", Kind: modelcheck.KindRequired},
		{Path: "WebsiteConfiguration.RedirectAllRequestsTo.HostName", Kind: modelcheck.KindRequired},
		{Path: "WebsiteConfiguration.RedirectAllRequestsTo.Protocol", Kind: modelcheck.KindEnum, Enum: []string{"http", "https"}},
		{Path: "WebsiteConfiguration.RoutingRules[].Redirect", Kind: modelcheck.KindRequired},
	},
	"PutObject": {
		{Path: "ACL", Kind: modelcheck.KindEnum, Enum: []string{"authenticated-read", "aws-exec-read", "bucket-owner-read", "bucket-owner-full-control", "private", "public-read", "public-read-write"}},
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"XXHASH128", "CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5", "SHA256", "XXHASH64", "XXHASH3"}},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "ObjectLockLegalHoldStatus", Kind: modelcheck.KindEnum, Enum: []string{"OFF", "ON"}},
		{Path: "ObjectLockMode", Kind: modelcheck.KindEnum, Enum: []string{"GOVERNANCE", "COMPLIANCE"}},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
		{Path: "ServerSideEncryption", Kind: modelcheck.KindEnum, Enum: []string{"aws:fsx", "aws:backup", "aws:kms", "aws:kms:dsse", "AES256"}},
		{Path: "StorageClass", Kind: modelcheck.KindEnum, Enum: []string{"FSX_OPENZFS", "REDUCED_REDUNDANCY", "GLACIER", "GLACIER_IR", "ONEZONE_IA", "INTELLIGENT_TIERING", "AWS_BACKUP_LOW_COST_WARM", "STANDARD_IA", "DEEP_ARCHIVE", "OUTPOSTS", "EXPRESS_ONEZONE", "FSX_ONTAP", "AWS_BACKUP_WARM", "STANDARD", "SNOW"}},
	},
	"PutObjectAcl": {
		{Path: "ACL", Kind: modelcheck.KindEnum, Enum: []string{"aws-exec-read", "bucket-owner-read", "bucket-owner-full-control", "private", "public-read", "public-read-write", "authenticated-read"}},
		{Path: "AccessControlPolicy.Grants[].Grantee.Type", Kind: modelcheck.KindRequired},
		{Path: "AccessControlPolicy.Grants[].Permission", Kind: modelcheck.KindEnum, Enum: []string{"WRITE_ACP", "READ", "READ_ACP", "FULL_CONTROL", "WRITE"}},
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"CRC64NVME", "SHA512", "MD5", "SHA256", "XXHASH64", "XXHASH3", "XXHASH128", "CRC32", "CRC32C", "SHA1"}},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
	},
	"PutObjectLegalHold": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"XXHASH64", "XXHASH3", "XXHASH128", "CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5", "SHA256"}},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "LegalHold.Status", Kind: modelcheck.KindEnum, Enum: []string{"OFF", "ON"}},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
	},
	"PutObjectLockConfiguration": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5", "SHA256", "XXHASH64", "XXHASH3", "XXHASH128"}},
		{Path: "ObjectLockConfiguration.ObjectLockEnabled", Kind: modelcheck.KindEnum, Enum: []string{"Enabled"}},
		{Path: "ObjectLockConfiguration.Rule.DefaultRetention.Mode", Kind: modelcheck.KindEnum, Enum: []string{"GOVERNANCE", "COMPLIANCE"}},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
	},
	"PutObjectRetention": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5", "SHA256", "XXHASH64", "XXHASH3", "XXHASH128", "CRC32"}},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
		{Path: "Retention.Mode", Kind: modelcheck.KindEnum, Enum: []string{"GOVERNANCE", "COMPLIANCE"}},
	},
	"PutObjectTagging": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"SHA256", "XXHASH64", "XXHASH3", "XXHASH128", "CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5"}},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
		{Path: "Tagging", Kind: modelcheck.KindRequired},
		{Path: "Tagging.TagSet", Kind: modelcheck.KindRequired},
		{Path: "Tagging.TagSet[].Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Tagging.TagSet[].Key", Kind: modelcheck.KindRequired},
		{Path: "Tagging.TagSet[].Value", Kind: modelcheck.KindRequired},
	},
	"UploadPart": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "ChecksumAlgorithm", Kind: modelcheck.KindEnum, Enum: []string{"SHA256", "XXHASH64", "XXHASH3", "XXHASH128", "CRC32", "CRC32C", "SHA1", "CRC64NVME", "SHA512", "MD5"}},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "PartNumber", Kind: modelcheck.KindRequired},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
		{Path: "UploadId", Kind: modelcheck.KindRequired},
	},
	"UploadPartCopy": {
		{Path: "Bucket", Kind: modelcheck.KindRequired},
		{Path: "CopySource", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^\/?.+\/.+$`)},
		{Path: "CopySource", Kind: modelcheck.KindRequired},
		{Path: "Key", Kind: modelcheck.KindLength, Min: 1, Max: modelcheck.NoMax},
		{Path: "Key", Kind: modelcheck.KindRequired},
		{Path: "PartNumber", Kind: modelcheck.KindRequired},
		{Path: "RequestPayer", Kind: modelcheck.KindEnum, Enum: []string{"requester"}},
		{Path: "UploadId", Kind: modelcheck.KindRequired},
	},
}
