package gateway

// queryActions maps Query-protocol Action names to services, for requests that
// carry neither an X-Amz-Target header nor a SigV4 scope (SigV2-signed or
// unsigned curl). Only the three Query-speaking services appear here — STS,
// SNS, and legacy SQS — and their action vocabularies do not overlap.
var queryActions = map[string]string{
	// STS (complete).
	"AssumeRole":                 "sts",
	"AssumeRoleWithSAML":         "sts",
	"AssumeRoleWithWebIdentity":  "sts",
	"AssumeRoot":                 "sts",
	"DecodeAuthorizationMessage": "sts",
	"GetAccessKeyInfo":           "sts",
	"GetCallerIdentity":          "sts",
	"GetFederationToken":         "sts",
	"GetSessionToken":            "sts",

	// SNS (complete for the topic/subscription/publish surface).
	"AddPermission":                      "sns",
	"CheckIfPhoneNumberIsOptedOut":       "sns",
	"ConfirmSubscription":                "sns",
	"CreateTopic":                        "sns",
	"DeleteTopic":                        "sns",
	"GetDataProtectionPolicy":            "sns",
	"GetSubscriptionAttributes":          "sns",
	"GetTopicAttributes":                 "sns",
	"ListOriginationNumbers":             "sns",
	"ListPhoneNumbersOptedOut":           "sns",
	"ListSubscriptions":                  "sns",
	"ListSubscriptionsByTopic":           "sns",
	"ListTagsForResource":                "sns",
	"ListTopics":                         "sns",
	"OptInPhoneNumber":                   "sns",
	"Publish":                            "sns",
	"PublishBatch":                       "sns",
	"PutDataProtectionPolicy":            "sns",
	"RemovePermission":                   "sns",
	"SetSubscriptionAttributes":          "sns",
	"SetTopicAttributes":                 "sns",
	"Subscribe":                          "sns",
	"TagResource":                        "sns",
	"Unsubscribe":                        "sns",
	"UntagResource":                      "sns",
	"CreatePlatformApplication":          "sns",
	"CreatePlatformEndpoint":             "sns",
	"CreateSMSSandboxPhoneNumber":        "sns",
	"DeleteEndpoint":                     "sns",
	"DeletePlatformApplication":          "sns",
	"DeleteSMSSandboxPhoneNumber":        "sns",
	"GetEndpointAttributes":              "sns",
	"GetPlatformApplicationAttributes":   "sns",
	"GetSMSAttributes":                   "sns",
	"GetSMSSandboxAccountStatus":         "sns",
	"ListEndpointsByPlatformApplication": "sns",
	"ListPlatformApplications":           "sns",
	"ListSMSSandboxPhoneNumbers":         "sns",
	"SetEndpointAttributes":              "sns",
	"SetPlatformApplicationAttributes":   "sns",
	"SetSMSAttributes":                   "sns",
	"VerifySMSSandboxPhoneNumber":        "sns",

	// SQS legacy Query protocol (complete, except AddPermission and
	// RemovePermission, which exist in BOTH SNS and SQS: the map above routes
	// those two to SNS. An SQS caller hitting that edge is one that sends bare
	// unsigned Query — real SDKs sign (scope "sqs") or use the JSON protocol,
	// either of which routes correctly before this table is consulted.
	"CancelMessageMoveTask":        "sqs",
	"ChangeMessageVisibility":      "sqs",
	"ChangeMessageVisibilityBatch": "sqs",
	"CreateQueue":                  "sqs",
	"DeleteMessage":                "sqs",
	"DeleteMessageBatch":           "sqs",
	"DeleteQueue":                  "sqs",
	"GetQueueAttributes":           "sqs",
	"GetQueueUrl":                  "sqs",
	"ListDeadLetterSourceQueues":   "sqs",
	"ListMessageMoveTasks":         "sqs",
	"ListQueueTags":                "sqs",
	"ListQueues":                   "sqs",
	"PurgeQueue":                   "sqs",
	"ReceiveMessage":               "sqs",
	"SendMessage":                  "sqs",
	"SendMessageBatch":             "sqs",
	"SetQueueAttributes":           "sqs",
	"StartMessageMoveTask":         "sqs",
	"TagQueue":                     "sqs",
	"UntagQueue":                   "sqs",
}
