package lambda

// Lambda's model-derived input validation: the constraint tables, walked
// by internal/modelcheck, and the route table that says which operation a
// request is.
//
// Lambda speaks restJson1. There is no target header naming the operation
// and no single encoded body — the input is spread across the URI, the query
// string and the JSON body — so the validator has to identify the operation
// from the method and the path before it can look up anything. Both tables are
// generated from AWS's own service model, so a route and the constraints it
// selects cannot drift apart, and both are replayed case by case in
// lambda/rejection_parity_test.go.

import (
	"regexp"

	"github.com/doze-dev/doze-aws/internal/modelcheck"
)

// route is one operation's REST binding. Segs is the path template with an
// empty string where a label goes, and Labels names that label.
type route struct {
	Op     string
	Method string
	Segs   []string
	Labels []string
	// Query maps a query-string parameter to the input member it carries, for
	// the members the model binds with @httpQuery, and QueryList names the ones
	// that arrive as a repeated parameter rather than a single value.
	Query     map[string]string
	QueryList map[string]bool
	// Header maps a header name to the input member it carries.
	Header map[string]string
}

// routes are ordered most-specific first, so a longer template wins over a
// shorter one that would also match.
var routes = []route{
	{Op: "DeleteAlias", Method: "DELETE", Segs: []string{"2015-03-31", "functions", "", "aliases", ""}, Labels: []string{"", "", "FunctionName", "", "Name"}},
	{Op: "GetAlias", Method: "GET", Segs: []string{"2015-03-31", "functions", "", "aliases", ""}, Labels: []string{"", "", "FunctionName", "", "Name"}},
	{Op: "RemovePermission", Method: "DELETE", Segs: []string{"2015-03-31", "functions", "", "policy", ""}, Labels: []string{"", "", "FunctionName", "", "StatementId"}, Query: map[string]string{"Qualifier": "Qualifier", "RevisionId": "RevisionId"}},
	{Op: "DeleteLayerVersion", Method: "DELETE", Segs: []string{"2018-10-31", "layers", "", "versions", ""}, Labels: []string{"", "", "LayerName", "", "VersionNumber"}},
	{Op: "GetLayerVersion", Method: "GET", Segs: []string{"2018-10-31", "layers", "", "versions", ""}, Labels: []string{"", "", "LayerName", "", "VersionNumber"}},
	{Op: "ListFunctionEventInvokeConfigs", Method: "GET", Segs: []string{"2019-09-25", "functions", "", "event-invoke-config", "list"}, Labels: []string{"", "", "FunctionName", "", ""}, Query: map[string]string{"Marker": "Marker", "MaxItems": "MaxItems"}},
	{Op: "CreateAlias", Method: "POST", Segs: []string{"2015-03-31", "functions", "", "aliases"}, Labels: []string{"", "", "FunctionName", ""}},
	{Op: "ListAliases", Method: "GET", Segs: []string{"2015-03-31", "functions", "", "aliases"}, Labels: []string{"", "", "FunctionName", ""}, Query: map[string]string{"FunctionVersion": "FunctionVersion", "Marker": "Marker", "MaxItems": "MaxItems"}},
	{Op: "UpdateFunctionCode", Method: "PUT", Segs: []string{"2015-03-31", "functions", "", "code"}, Labels: []string{"", "", "FunctionName", ""}},
	{Op: "GetFunctionConfiguration", Method: "GET", Segs: []string{"2015-03-31", "functions", "", "configuration"}, Labels: []string{"", "", "FunctionName", ""}, Query: map[string]string{"Qualifier": "Qualifier"}},
	{Op: "UpdateFunctionConfiguration", Method: "PUT", Segs: []string{"2015-03-31", "functions", "", "configuration"}, Labels: []string{"", "", "FunctionName", ""}},
	{Op: "Invoke", Method: "POST", Segs: []string{"2015-03-31", "functions", "", "invocations"}, Labels: []string{"", "", "FunctionName", ""}, Query: map[string]string{"Qualifier": "Qualifier"}, Header: map[string]string{"X-Amz-Client-Context": "ClientContext", "X-Amz-Durable-Execution-Name": "DurableExecutionName", "X-Amz-Invocation-Type": "InvocationType", "X-Amz-Log-Type": "LogType", "X-Amz-Tenant-Id": "TenantId"}},
	{Op: "AddPermission", Method: "POST", Segs: []string{"2015-03-31", "functions", "", "policy"}, Labels: []string{"", "", "FunctionName", ""}, Query: map[string]string{"Qualifier": "Qualifier"}},
	{Op: "GetPolicy", Method: "GET", Segs: []string{"2015-03-31", "functions", "", "policy"}, Labels: []string{"", "", "FunctionName", ""}, Query: map[string]string{"Qualifier": "Qualifier"}},
	{Op: "ListVersionsByFunction", Method: "GET", Segs: []string{"2015-03-31", "functions", "", "versions"}, Labels: []string{"", "", "FunctionName", ""}, Query: map[string]string{"Marker": "Marker", "MaxItems": "MaxItems"}},
	{Op: "PublishVersion", Method: "POST", Segs: []string{"2015-03-31", "functions", "", "versions"}, Labels: []string{"", "", "FunctionName", ""}},
	{Op: "DeleteFunctionConcurrency", Method: "DELETE", Segs: []string{"2017-10-31", "functions", "", "concurrency"}, Labels: []string{"", "", "FunctionName", ""}},
	{Op: "PutFunctionConcurrency", Method: "PUT", Segs: []string{"2017-10-31", "functions", "", "concurrency"}, Labels: []string{"", "", "FunctionName", ""}},
	{Op: "ListLayerVersions", Method: "GET", Segs: []string{"2018-10-31", "layers", "", "versions"}, Labels: []string{"", "", "LayerName", ""}, Query: map[string]string{"CompatibleArchitecture": "CompatibleArchitecture", "CompatibleRuntime": "CompatibleRuntime", "Marker": "Marker", "MaxItems": "MaxItems"}},
	{Op: "PublishLayerVersion", Method: "POST", Segs: []string{"2018-10-31", "layers", "", "versions"}, Labels: []string{"", "", "LayerName", ""}},
	{Op: "DeleteFunctionEventInvokeConfig", Method: "DELETE", Segs: []string{"2019-09-25", "functions", "", "event-invoke-config"}, Labels: []string{"", "", "FunctionName", ""}, Query: map[string]string{"Qualifier": "Qualifier"}},
	{Op: "GetFunctionEventInvokeConfig", Method: "GET", Segs: []string{"2019-09-25", "functions", "", "event-invoke-config"}, Labels: []string{"", "", "FunctionName", ""}, Query: map[string]string{"Qualifier": "Qualifier"}},
	{Op: "PutFunctionEventInvokeConfig", Method: "PUT", Segs: []string{"2019-09-25", "functions", "", "event-invoke-config"}, Labels: []string{"", "", "FunctionName", ""}, Query: map[string]string{"Qualifier": "Qualifier"}},
	{Op: "UpdateFunctionEventInvokeConfig", Method: "POST", Segs: []string{"2019-09-25", "functions", "", "event-invoke-config"}, Labels: []string{"", "", "FunctionName", ""}, Query: map[string]string{"Qualifier": "Qualifier"}},
	{Op: "GetFunctionConcurrency", Method: "GET", Segs: []string{"2019-09-30", "functions", "", "concurrency"}, Labels: []string{"", "", "FunctionName", ""}},
	{Op: "DeleteFunctionCodeSigningConfig", Method: "DELETE", Segs: []string{"2020-06-30", "functions", "", "code-signing-config"}, Labels: []string{"", "", "FunctionName", ""}},
	{Op: "GetFunctionCodeSigningConfig", Method: "GET", Segs: []string{"2020-06-30", "functions", "", "code-signing-config"}, Labels: []string{"", "", "FunctionName", ""}},
	{Op: "PutFunctionCodeSigningConfig", Method: "PUT", Segs: []string{"2020-06-30", "functions", "", "code-signing-config"}, Labels: []string{"", "", "FunctionName", ""}},
	{Op: "CreateFunctionUrlConfig", Method: "POST", Segs: []string{"2021-10-31", "functions", "", "url"}, Labels: []string{"", "", "FunctionName", ""}, Query: map[string]string{"Qualifier": "Qualifier"}},
	{Op: "DeleteFunctionUrlConfig", Method: "DELETE", Segs: []string{"2021-10-31", "functions", "", "url"}, Labels: []string{"", "", "FunctionName", ""}, Query: map[string]string{"Qualifier": "Qualifier"}},
	{Op: "GetFunctionUrlConfig", Method: "GET", Segs: []string{"2021-10-31", "functions", "", "url"}, Labels: []string{"", "", "FunctionName", ""}, Query: map[string]string{"Qualifier": "Qualifier"}},
	{Op: "UpdateFunctionUrlConfig", Method: "PUT", Segs: []string{"2021-10-31", "functions", "", "url"}, Labels: []string{"", "", "FunctionName", ""}, Query: map[string]string{"Qualifier": "Qualifier"}},
	{Op: "ListFunctionUrlConfigs", Method: "GET", Segs: []string{"2021-10-31", "functions", "", "urls"}, Labels: []string{"", "", "FunctionName", ""}, Query: map[string]string{"Marker": "Marker", "MaxItems": "MaxItems"}},
	{Op: "DeleteEventSourceMapping", Method: "DELETE", Segs: []string{"2015-03-31", "event-source-mappings", ""}, Labels: []string{"", "", "UUID"}},
	{Op: "GetEventSourceMapping", Method: "GET", Segs: []string{"2015-03-31", "event-source-mappings", ""}, Labels: []string{"", "", "UUID"}},
	{Op: "UpdateEventSourceMapping", Method: "PUT", Segs: []string{"2015-03-31", "event-source-mappings", ""}, Labels: []string{"", "", "UUID"}},
	{Op: "DeleteFunction", Method: "DELETE", Segs: []string{"2015-03-31", "functions", ""}, Labels: []string{"", "", "FunctionName"}, Query: map[string]string{"Qualifier": "Qualifier"}},
	{Op: "GetFunction", Method: "GET", Segs: []string{"2015-03-31", "functions", ""}, Labels: []string{"", "", "FunctionName"}, Query: map[string]string{"Qualifier": "Qualifier"}},
	{Op: "ListTags", Method: "GET", Segs: []string{"2017-03-31", "tags", ""}, Labels: []string{"", "", "Resource"}},
	{Op: "TagResource", Method: "POST", Segs: []string{"2017-03-31", "tags", ""}, Labels: []string{"", "", "Resource"}},
	{Op: "UntagResource", Method: "DELETE", Segs: []string{"2017-03-31", "tags", ""}, Labels: []string{"", "", "Resource"}, Query: map[string]string{"tagKeys": "TagKeys"}, QueryList: map[string]bool{"TagKeys": true}},
	{Op: "CreateEventSourceMapping", Method: "POST", Segs: []string{"2015-03-31", "event-source-mappings"}, Labels: []string{"", ""}},
	{Op: "ListEventSourceMappings", Method: "GET", Segs: []string{"2015-03-31", "event-source-mappings"}, Labels: []string{"", ""}, Query: map[string]string{"EventSourceArn": "EventSourceArn", "FunctionName": "FunctionName", "Marker": "Marker", "MaxItems": "MaxItems"}},
	{Op: "CreateFunction", Method: "POST", Segs: []string{"2015-03-31", "functions"}, Labels: []string{"", ""}},
	{Op: "ListFunctions", Method: "GET", Segs: []string{"2015-03-31", "functions"}, Labels: []string{"", ""}, Query: map[string]string{"FunctionVersion": "FunctionVersion", "Marker": "Marker", "MasterRegion": "MasterRegion", "MaxItems": "MaxItems"}},
	{Op: "ListLayers", Method: "GET", Segs: []string{"2018-10-31", "layers"}, Labels: []string{"", ""}, Query: map[string]string{"CompatibleArchitecture": "CompatibleArchitecture", "CompatibleRuntime": "CompatibleRuntime", "Marker": "Marker", "MaxItems": "MaxItems"}},
}

var constraintTables = map[string][]modelcheck.Constraint{
	"AddPermission": {
		{Path: "Action", Kind: modelcheck.KindLength, Min: 0, Max: 10000},
		{Path: "Action", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(lambda:[*]|lambda:[a-zA-Z]+|[*])$`)},
		{Path: "Action", Kind: modelcheck.KindRequired},
		{Path: "EventSourceToken", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "EventSourceToken", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9._\-]+$`)},
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "FunctionUrlAuthType", Kind: modelcheck.KindEnum, Enum: []string{"NONE", "AWS_IAM"}},
		{Path: "Principal", Kind: modelcheck.KindLength, Min: 0, Max: 2048},
		{Path: "Principal", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[^\s]+$`)},
		{Path: "Principal", Kind: modelcheck.KindRequired},
		{Path: "PrincipalOrgID", Kind: modelcheck.KindLength, Min: 12, Max: 34},
		{Path: "PrincipalOrgID", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^o-[a-z0-9]{10,32}$`)},
		{Path: "Qualifier", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Qualifier", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^\$(LATEST(\.PUBLISHED)?)|[a-zA-Z0-9-_$]+$`)},
		{Path: "SourceAccount", Kind: modelcheck.KindLength, Min: 0, Max: 12},
		{Path: "SourceAccount", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^\d{12}$`)},
		{Path: "SourceArn", Kind: modelcheck.KindLength, Min: 0, Max: 10000},
		{Path: "SourceArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1})?:(\d{12})?:(.*)$`)},
		{Path: "StatementId", Kind: modelcheck.KindLength, Min: 1, Max: 100},
		{Path: "StatementId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^([a-zA-Z0-9-_]+)$`)},
		{Path: "StatementId", Kind: modelcheck.KindRequired},
	},
	"CreateAlias": {
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:)?((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "FunctionVersion", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "FunctionVersion", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(\$LATEST(\.PUBLISHED)?|[0-9]+)$`)},
		{Path: "FunctionVersion", Kind: modelcheck.KindRequired},
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Name", Kind: modelcheck.KindRequired},
		{Path: "RoutingConfig.AdditionalVersionWeights{}", Kind: modelcheck.KindRange, Min: 0, Max: 1},
	},
	"CreateEventSourceMapping": {
		{Path: "AmazonManagedKafkaEventSourceConfig.ConsumerGroupId", Kind: modelcheck.KindLength, Min: 1, Max: 200},
		{Path: "AmazonManagedKafkaEventSourceConfig.ConsumerGroupId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ a-zA-Z0-9-\/*:_+=.@-]*$`)},
		{Path: "AmazonManagedKafkaEventSourceConfig.SchemaRegistryConfig.EventRecordFormat", Kind: modelcheck.KindEnum, Enum: []string{"JSON", "SOURCE"}},
		{Path: "AmazonManagedKafkaEventSourceConfig.SchemaRegistryConfig.SchemaRegistryURI", Kind: modelcheck.KindLength, Min: 1, Max: 10000},
		{Path: "AmazonManagedKafkaEventSourceConfig.SchemaRegistryConfig.SchemaRegistryURI", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9-\/*:_+=.@-]*$`)},
		{Path: "BatchSize", Kind: modelcheck.KindRange, Min: 1, Max: 10000},
		{Path: "DestinationConfig.OnFailure.Destination", Kind: modelcheck.KindLength, Min: 0, Max: 350},
		{Path: "DestinationConfig.OnFailure.Destination", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^$|kafka://([^.]([a-zA-Z0-9\-_.]{0,248}))|arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1})?:(\d{12})?:(.*)$`)},
		{Path: "DestinationConfig.OnSuccess.Destination", Kind: modelcheck.KindLength, Min: 0, Max: 350},
		{Path: "DestinationConfig.OnSuccess.Destination", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^$|kafka://([^.]([a-zA-Z0-9\-_.]{0,248}))|arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1})?:(\d{12})?:(.*)$`)},
		{Path: "DocumentDBEventSourceConfig.CollectionName", Kind: modelcheck.KindLength, Min: 1, Max: 57},
		{Path: "DocumentDBEventSourceConfig.DatabaseName", Kind: modelcheck.KindLength, Min: 1, Max: 63},
		{Path: "DocumentDBEventSourceConfig.DatabaseName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[^ /\.$\x22]*$`)},
		{Path: "DocumentDBEventSourceConfig.FullDocument", Kind: modelcheck.KindEnum, Enum: []string{"UpdateLookup", "Default"}},
		{Path: "EventSourceArn", Kind: modelcheck.KindLength, Min: 0, Max: 10000},
		{Path: "EventSourceArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1})?:(\d{12})?:(.*)$`)},
		{Path: "FilterCriteria.Filters[].Pattern", Kind: modelcheck.KindLength, Min: 0, Max: 4096},
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "FunctionResponseTypes[]", Kind: modelcheck.KindEnum, Enum: []string{"ReportBatchItemFailures"}},
		{Path: "KMSKeyArn", Kind: modelcheck.KindLength, Min: 0, Max: 10000},
		{Path: "LoggingConfig.SystemLogLevel", Kind: modelcheck.KindEnum, Enum: []string{"DEBUG", "INFO", "WARN"}},
		{Path: "MaximumBatchingWindowInSeconds", Kind: modelcheck.KindRange, Min: 0, Max: 300},
		{Path: "MaximumRecordAgeInSeconds", Kind: modelcheck.KindRange, Min: -1, Max: 604800},
		{Path: "MaximumRetryAttempts", Kind: modelcheck.KindRange, Min: -1, Max: 10000},
		{Path: "MetricsConfig.Metrics[]", Kind: modelcheck.KindEnum, Enum: []string{"EventCount", "ErrorCount", "KafkaMetrics"}},
		{Path: "ParallelizationFactor", Kind: modelcheck.KindRange, Min: 1, Max: 10},
		{Path: "ProvisionedPollerConfig.MaximumPollers", Kind: modelcheck.KindRange, Min: 1, Max: 10000},
		{Path: "ProvisionedPollerConfig.MinimumPollers", Kind: modelcheck.KindRange, Min: 1, Max: 200},
		{Path: "ProvisionedPollerConfig.PollerGroupName", Kind: modelcheck.KindLength, Min: 0, Max: 128},
		{Path: "ProvisionedPollerConfig.PollerGroupName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9-_]*$`)},
		{Path: "Queues[]", Kind: modelcheck.KindLength, Min: 1, Max: 1000},
		{Path: "ScalingConfig.MaximumConcurrency", Kind: modelcheck.KindRange, Min: 2, Max: 1000},
		{Path: "SelfManagedEventSource.Endpoints{}[]", Kind: modelcheck.KindLength, Min: 1, Max: 300},
		{Path: "SelfManagedEventSource.Endpoints{}[]", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9]):[0-9]{1,5}$`)},
		{Path: "SelfManagedKafkaEventSourceConfig.ConsumerGroupId", Kind: modelcheck.KindLength, Min: 1, Max: 200},
		{Path: "SelfManagedKafkaEventSourceConfig.ConsumerGroupId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ a-zA-Z0-9-\/*:_+=.@-]*$`)},
		{Path: "SelfManagedKafkaEventSourceConfig.SchemaRegistryConfig.EventRecordFormat", Kind: modelcheck.KindEnum, Enum: []string{"JSON", "SOURCE"}},
		{Path: "SelfManagedKafkaEventSourceConfig.SchemaRegistryConfig.SchemaRegistryURI", Kind: modelcheck.KindLength, Min: 1, Max: 10000},
		{Path: "SelfManagedKafkaEventSourceConfig.SchemaRegistryConfig.SchemaRegistryURI", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9-\/*:_+=.@-]*$`)},
		{Path: "SourceAccessConfigurations[].Type", Kind: modelcheck.KindEnum, Enum: []string{"SERVER_ROOT_CA_CERTIFICATE", "BASIC_AUTH", "VPC_SUBNET", "VPC_SECURITY_GROUP", "SASL_SCRAM_512_AUTH", "SASL_SCRAM_256_AUTH", "VIRTUAL_HOST", "CLIENT_CERTIFICATE_TLS_AUTH"}},
		{Path: "SourceAccessConfigurations[].URI", Kind: modelcheck.KindLength, Min: 1, Max: 200},
		{Path: "SourceAccessConfigurations[].URI", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ a-zA-Z0-9-\/*:_+=.@-]*$`)},
		{Path: "StartingPosition", Kind: modelcheck.KindEnum, Enum: []string{"TRIM_HORIZON", "LATEST", "AT_TIMESTAMP"}},
		{Path: "Tags{}", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Tags{}", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$`)},
		{Path: "Topics[]", Kind: modelcheck.KindLength, Min: 1, Max: 249},
		{Path: "Topics[]", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[^.]([a-zA-Z0-9\-_.]+)$`)},
		{Path: "TumblingWindowInSeconds", Kind: modelcheck.KindRange, Min: 0, Max: 900},
	},
	"CreateFunction": {
		{Path: "Architectures[]", Kind: modelcheck.KindEnum, Enum: []string{"x86_64", "arm64"}},
		{Path: "CapacityProviderConfig.LambdaManagedInstancesCapacityProviderConfig", Kind: modelcheck.KindRequired},
		{Path: "CapacityProviderConfig.LambdaManagedInstancesCapacityProviderConfig.CapacityProviderArn", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "CapacityProviderConfig.LambdaManagedInstancesCapacityProviderConfig.CapacityProviderArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws[a-zA-Z-]*:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:capacity-provider:[a-zA-Z0-9-_]+$`)},
		{Path: "CapacityProviderConfig.LambdaManagedInstancesCapacityProviderConfig.CapacityProviderArn", Kind: modelcheck.KindRequired},
		{Path: "CapacityProviderConfig.LambdaManagedInstancesCapacityProviderConfig.ExecutionEnvironmentMemoryGiBPerVCpu", Kind: modelcheck.KindRange, Min: 2, Max: 8},
		{Path: "CapacityProviderConfig.LambdaManagedInstancesCapacityProviderConfig.PerExecutionEnvironmentMaxConcurrency", Kind: modelcheck.KindRange, Min: 1, Max: 1600},
		{Path: "Code", Kind: modelcheck.KindRequired},
		{Path: "Code.S3Bucket", Kind: modelcheck.KindLength, Min: 3, Max: 63},
		{Path: "Code.S3Key", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "Code.S3Key", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^.*$`)},
		{Path: "Code.S3ObjectStorageMode", Kind: modelcheck.KindEnum, Enum: []string{"REFERENCE", "COPY"}},
		{Path: "Code.S3ObjectVersion", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "Code.S3ObjectVersion", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^.*$`)},
		{Path: "Code.SourceKMSKeyArn", Kind: modelcheck.KindLength, Min: 0, Max: 10000},
		{Path: "CodeSigningConfigArn", Kind: modelcheck.KindLength, Min: 0, Max: 200},
		{Path: "CodeSigningConfigArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:code-signing-config:csc-[a-z0-9]{17}$`)},
		{Path: "DeadLetterConfig.TargetArn", Kind: modelcheck.KindLength, Min: 0, Max: 10000},
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "DurableConfig.ExecutionTimeout", Kind: modelcheck.KindRange, Min: 1, Max: 31622400},
		{Path: "DurableConfig.KMSKeyArn", Kind: modelcheck.KindLength, Min: 0, Max: 10000},
		{Path: "DurableConfig.RetentionPeriodInDays", Kind: modelcheck.KindRange, Min: 1, Max: 90},
		{Path: "EphemeralStorage.Size", Kind: modelcheck.KindRange, Min: 512, Max: 10240},
		{Path: "EphemeralStorage.Size", Kind: modelcheck.KindRequired},
		{Path: "FileSystemConfigs[].Arn", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "FileSystemConfigs[].Arn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws[a-zA-Z-]*:elasticfilesystem:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:access-point/fsap-[a-f0-9]{17}$|^arn:aws[-a-z]*:s3files:[0-9a-z-:]+:file-system/fs-[0-9a-f]{17,40}/access-point/fsap-[0-9a-f]{17,40}$`)},
		{Path: "FileSystemConfigs[].Arn", Kind: modelcheck.KindRequired},
		{Path: "FileSystemConfigs[].LocalMountPath", Kind: modelcheck.KindLength, Min: 0, Max: 160},
		{Path: "FileSystemConfigs[].LocalMountPath", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^/mnt/[a-zA-Z0-9-_.]+$`)},
		{Path: "FileSystemConfigs[].LocalMountPath", Kind: modelcheck.KindRequired},
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:)?((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "Handler", Kind: modelcheck.KindLength, Min: 0, Max: 128},
		{Path: "Handler", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[^\s]+$`)},
		{Path: "ImageConfig.WorkingDirectory", Kind: modelcheck.KindLength, Min: 0, Max: 1000},
		{Path: "KMSKeyArn", Kind: modelcheck.KindLength, Min: 0, Max: 10000},
		{Path: "Layers[]", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "Layers[]", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^((arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:layer:[a-zA-Z0-9-_]+:[0-9]+)|(arn:[a-zA-Z0-9-]+:lambda:::awslayer:[a-zA-Z0-9-_]+))$`)},
		{Path: "LoggingConfig.ApplicationLogLevel", Kind: modelcheck.KindEnum, Enum: []string{"FATAL", "TRACE", "DEBUG", "INFO", "WARN", "ERROR"}},
		{Path: "LoggingConfig.LogFormat", Kind: modelcheck.KindEnum, Enum: []string{"JSON", "Text"}},
		{Path: "LoggingConfig.LogGroup", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "LoggingConfig.LogGroup", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_/#A-Za-z0-9]+$`)},
		{Path: "LoggingConfig.SystemLogLevel", Kind: modelcheck.KindEnum, Enum: []string{"WARN", "DEBUG", "INFO"}},
		{Path: "MemorySize", Kind: modelcheck.KindRange, Min: 128, Max: 32768},
		{Path: "PackageType", Kind: modelcheck.KindEnum, Enum: []string{"Image", "Zip"}},
		{Path: "PublishTo", Kind: modelcheck.KindEnum, Enum: []string{"LATEST_PUBLISHED"}},
		{Path: "Role", Kind: modelcheck.KindLength, Min: 0, Max: 10000},
		{Path: "Role", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$`)},
		{Path: "Role", Kind: modelcheck.KindRequired},
		{Path: "Runtime", Kind: modelcheck.KindEnum, Enum: []string{"python3.14", "nodejs18.x", "dotnet8", "nodejs4.3-edge", "ruby2.7", "ruby3.3", "provided", "nodejs26.x", "nodejs4.3", "nodejs24.x", "java11", "dotnetcore2.0", "go1.x", "python3.15", "java8.al2023", "nodejs10.x", "nodejs22.x", "java17", "python3.8", "dotnet6", "java8", "java21", "python3.9", "dotnetcore2.1", "dotnet10", "provided.al2", "java11.al2023", "java17.al2023", "nodejs", "nodejs6.10", "nodejs12.x", "nodejs20.x", "java8.al2", "python3.6", "python3.13", "python3.12", "nodejs16.x", "java25", "python2.7", "python3.7", "python3.10", "dotnetcore3.1", "ruby2.5", "nodejs14.x", "python3.11", "dotnetcore1.0", "ruby3.4", "ruby4.0", "provided.al2023", "nodejs8.10", "ruby3.2"}},
		{Path: "SnapStart.ApplyOn", Kind: modelcheck.KindEnum, Enum: []string{"PublishedVersions", "None"}},
		{Path: "Tags{}", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Tags{}", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$`)},
		{Path: "TenancyConfig.TenantIsolationMode", Kind: modelcheck.KindEnum, Enum: []string{"PER_TENANT"}},
		{Path: "TenancyConfig.TenantIsolationMode", Kind: modelcheck.KindRequired},
		{Path: "Timeout", Kind: modelcheck.KindRange, Min: 1, Max: 5400},
		{Path: "TracingConfig.Mode", Kind: modelcheck.KindEnum, Enum: []string{"Active", "PassThrough"}},
		{Path: "VpcConfig.SecurityGroupIds[]", Kind: modelcheck.KindLength, Min: 0, Max: 1024},
		{Path: "VpcConfig.SecurityGroupIds[]", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^sg-[0-9a-zA-Z]*$`)},
		{Path: "VpcConfig.SubnetIds[]", Kind: modelcheck.KindLength, Min: 0, Max: 1024},
		{Path: "VpcConfig.SubnetIds[]", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^subnet-[0-9a-z]*$`)},
	},
	"CreateFunctionUrlConfig": {
		{Path: "AuthType", Kind: modelcheck.KindEnum, Enum: []string{"NONE", "AWS_IAM"}},
		{Path: "AuthType", Kind: modelcheck.KindRequired},
		{Path: "Cors.AllowHeaders[]", Kind: modelcheck.KindLength, Min: 0, Max: 1024},
		{Path: "Cors.AllowMethods[]", Kind: modelcheck.KindLength, Min: 0, Max: 6},
		{Path: "Cors.AllowOrigins[]", Kind: modelcheck.KindLength, Min: 1, Max: 253},
		{Path: "Cors.ExposeHeaders[]", Kind: modelcheck.KindLength, Min: 0, Max: 1024},
		{Path: "Cors.MaxAge", Kind: modelcheck.KindRange, Min: 0, Max: 86400},
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "InvokeMode", Kind: modelcheck.KindEnum, Enum: []string{"RESPONSE_STREAM", "BUFFERED"}},
		{Path: "Qualifier", Kind: modelcheck.KindLength, Min: 1, Max: 128},
	},
	"DeleteAlias": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:)?((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Name", Kind: modelcheck.KindRequired},
	},
	"DeleteEventSourceMapping": {
		{Path: "UUID", Kind: modelcheck.KindLength, Min: 36, Max: 36},
		{Path: "UUID", Kind: modelcheck.KindRequired},
	},
	"DeleteFunction": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "Qualifier", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Qualifier", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^\$(LATEST(\.PUBLISHED)?)|[a-zA-Z0-9-_$]+$`)},
	},
	"DeleteFunctionCodeSigningConfig": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
	},
	"DeleteFunctionConcurrency": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:)?((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
	},
	"DeleteFunctionEventInvokeConfig": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "Qualifier", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Qualifier", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^\$(LATEST(\.PUBLISHED)?)|[a-zA-Z0-9-_$]+$`)},
	},
	"DeleteFunctionUrlConfig": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "Qualifier", Kind: modelcheck.KindLength, Min: 1, Max: 128},
	},
	"DeleteLayerVersion": {
		{Path: "LayerName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "LayerName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:layer:[a-zA-Z0-9-_]+)|[a-zA-Z0-9-_]+$`)},
		{Path: "LayerName", Kind: modelcheck.KindRequired},
		{Path: "VersionNumber", Kind: modelcheck.KindRequired},
	},
	"GetAlias": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:)?((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Name", Kind: modelcheck.KindRequired},
	},
	"GetEventSourceMapping": {
		{Path: "UUID", Kind: modelcheck.KindLength, Min: 36, Max: 36},
		{Path: "UUID", Kind: modelcheck.KindRequired},
	},
	"GetFunction": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "Qualifier", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Qualifier", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^\$(LATEST(\.PUBLISHED)?)|[a-zA-Z0-9-_$]+$`)},
	},
	"GetFunctionCodeSigningConfig": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
	},
	"GetFunctionConcurrency": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:)?((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
	},
	"GetFunctionConfiguration": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "Qualifier", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Qualifier", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^\$(LATEST(\.PUBLISHED)?)|[a-zA-Z0-9-_$]+$`)},
	},
	"GetFunctionEventInvokeConfig": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "Qualifier", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Qualifier", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^\$(LATEST(\.PUBLISHED)?)|[a-zA-Z0-9-_$]+$`)},
	},
	"GetFunctionUrlConfig": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "Qualifier", Kind: modelcheck.KindLength, Min: 1, Max: 128},
	},
	"GetLayerVersion": {
		{Path: "LayerName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "LayerName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:layer:[a-zA-Z0-9-_]+)|[a-zA-Z0-9-_]+$`)},
		{Path: "LayerName", Kind: modelcheck.KindRequired},
		{Path: "VersionNumber", Kind: modelcheck.KindRequired},
	},
	"GetPolicy": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "Qualifier", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Qualifier", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^\$(LATEST(\.PUBLISHED)?)|[a-zA-Z0-9-_$]+$`)},
	},
	"Invoke": {
		{Path: "DurableExecutionName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "DurableExecutionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9-_]+$`)},
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "InvocationType", Kind: modelcheck.KindEnum, Enum: []string{"Event", "RequestResponse", "DryRun"}},
		{Path: "LogType", Kind: modelcheck.KindEnum, Enum: []string{"None", "Tail"}},
		{Path: "Qualifier", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Qualifier", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^\$(LATEST(\.PUBLISHED)?)|[a-zA-Z0-9-_$]+$`)},
		{Path: "TenantId", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "TenantId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9\._:\/=+\-@ ]+$`)},
	},
	"ListAliases": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:)?((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "FunctionVersion", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "FunctionVersion", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(\$LATEST(\.PUBLISHED)?|[0-9]+)$`)},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 10000},
	},
	"ListEventSourceMappings": {
		{Path: "EventSourceArn", Kind: modelcheck.KindLength, Min: 0, Max: 10000},
		{Path: "EventSourceArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1})?:(\d{12})?:(.*)$`)},
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 10000},
	},
	"ListFunctionEventInvokeConfigs": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 50},
	},
	"ListFunctionUrlConfigs": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 50},
	},
	"ListFunctions": {
		{Path: "FunctionVersion", Kind: modelcheck.KindEnum, Enum: []string{"ALL"}},
		{Path: "MasterRegion", Kind: modelcheck.KindLength, Min: 1, Max: 50},
		{Path: "MasterRegion", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^ALL|(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}$`)},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 10000},
	},
	"ListLayerVersions": {
		{Path: "CompatibleArchitecture", Kind: modelcheck.KindEnum, Enum: []string{"x86_64", "arm64"}},
		{Path: "CompatibleRuntime", Kind: modelcheck.KindEnum, Enum: []string{"nodejs26.x", "nodejs4.3", "nodejs24.x", "java11", "dotnetcore2.0", "go1.x", "python3.15", "java8.al2023", "nodejs10.x", "nodejs22.x", "java17", "python3.8", "dotnet6", "java8", "java21", "python3.9", "dotnetcore2.1", "dotnet10", "provided.al2", "java11.al2023", "java17.al2023", "nodejs", "nodejs6.10", "nodejs12.x", "nodejs20.x", "java8.al2", "python3.6", "python3.13", "python3.12", "nodejs16.x", "java25", "python2.7", "python3.7", "python3.10", "dotnetcore3.1", "ruby2.5", "nodejs14.x", "python3.11", "dotnetcore1.0", "ruby3.4", "ruby4.0", "provided.al2023", "nodejs8.10", "ruby3.2", "python3.14", "nodejs18.x", "dotnet8", "nodejs4.3-edge", "ruby2.7", "ruby3.3", "provided"}},
		{Path: "LayerName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "LayerName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:layer:[a-zA-Z0-9-_]+)|[a-zA-Z0-9-_]+$`)},
		{Path: "LayerName", Kind: modelcheck.KindRequired},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 50},
	},
	"ListLayers": {
		{Path: "CompatibleArchitecture", Kind: modelcheck.KindEnum, Enum: []string{"x86_64", "arm64"}},
		{Path: "CompatibleRuntime", Kind: modelcheck.KindEnum, Enum: []string{"nodejs6.10", "nodejs12.x", "nodejs20.x", "java8.al2", "python3.6", "python3.13", "python3.12", "nodejs16.x", "java25", "python2.7", "python3.7", "python3.10", "dotnetcore3.1", "ruby2.5", "nodejs14.x", "python3.11", "dotnetcore1.0", "ruby3.4", "ruby4.0", "provided.al2023", "nodejs8.10", "ruby3.2", "python3.14", "nodejs18.x", "dotnet8", "nodejs4.3-edge", "ruby2.7", "ruby3.3", "provided", "nodejs26.x", "nodejs4.3", "nodejs24.x", "java11", "dotnetcore2.0", "go1.x", "python3.15", "java8.al2023", "nodejs10.x", "nodejs22.x", "java17", "python3.8", "dotnet6", "java8", "java21", "python3.9", "dotnetcore2.1", "dotnet10", "provided.al2", "java11.al2023", "java17.al2023", "nodejs"}},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 50},
	},
	"ListTags": {
		{Path: "Resource", Kind: modelcheck.KindLength, Min: 1, Max: 10000},
		{Path: "Resource", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:(aws[a-zA-Z-]*):lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:(function:[a-zA-Z0-9-_]+(:(\$LATEST|[a-zA-Z0-9-_]+))?|code-signing-config:csc-[a-z0-9]{17}|event-source-mapping:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|(capacity-provider|network-connector):[a-zA-Z0-9-_]{1,64})$`)},
		{Path: "Resource", Kind: modelcheck.KindRequired},
	},
	"ListVersionsByFunction": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 10000},
	},
	"PublishLayerVersion": {
		{Path: "CompatibleArchitectures[]", Kind: modelcheck.KindEnum, Enum: []string{"x86_64", "arm64"}},
		{Path: "CompatibleRuntimes[]", Kind: modelcheck.KindEnum, Enum: []string{"nodejs18.x", "dotnet8", "nodejs4.3-edge", "ruby2.7", "ruby3.3", "provided", "nodejs26.x", "nodejs4.3", "nodejs24.x", "java11", "dotnetcore2.0", "go1.x", "python3.15", "java8.al2023", "nodejs10.x", "nodejs22.x", "java17", "python3.8", "dotnet6", "java8", "java21", "python3.9", "dotnetcore2.1", "dotnet10", "provided.al2", "java11.al2023", "java17.al2023", "nodejs", "nodejs6.10", "nodejs12.x", "nodejs20.x", "java8.al2", "python3.6", "python3.13", "python3.12", "nodejs16.x", "java25", "python2.7", "python3.7", "python3.10", "dotnetcore3.1", "ruby2.5", "nodejs14.x", "python3.11", "dotnetcore1.0", "ruby3.4", "ruby4.0", "provided.al2023", "nodejs8.10", "ruby3.2", "python3.14"}},
		{Path: "Content", Kind: modelcheck.KindRequired},
		{Path: "Content.S3Bucket", Kind: modelcheck.KindLength, Min: 3, Max: 63},
		{Path: "Content.S3Key", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "Content.S3Key", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^.*$`)},
		{Path: "Content.S3ObjectStorageMode", Kind: modelcheck.KindEnum, Enum: []string{"COPY", "REFERENCE"}},
		{Path: "Content.S3ObjectVersion", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "Content.S3ObjectVersion", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^.*$`)},
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "LayerName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "LayerName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:layer:[a-zA-Z0-9-_]+)|[a-zA-Z0-9-_]+$`)},
		{Path: "LayerName", Kind: modelcheck.KindRequired},
		{Path: "LicenseInfo", Kind: modelcheck.KindLength, Min: 0, Max: 512},
		{Path: "LicenseInfo", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^.*$`)},
	},
	"PublishVersion": {
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:)?((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "PublishTo", Kind: modelcheck.KindEnum, Enum: []string{"LATEST_PUBLISHED"}},
	},
	"PutFunctionCodeSigningConfig": {
		{Path: "CodeSigningConfigArn", Kind: modelcheck.KindLength, Min: 0, Max: 200},
		{Path: "CodeSigningConfigArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:code-signing-config:csc-[a-z0-9]{17}$`)},
		{Path: "CodeSigningConfigArn", Kind: modelcheck.KindRequired},
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
	},
	"PutFunctionConcurrency": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:)?((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "ReservedConcurrentExecutions", Kind: modelcheck.KindRange, Min: 0, Max: modelcheck.NoMax},
		{Path: "ReservedConcurrentExecutions", Kind: modelcheck.KindRequired},
	},
	"PutFunctionEventInvokeConfig": {
		{Path: "DestinationConfig.OnFailure.Destination", Kind: modelcheck.KindLength, Min: 0, Max: 350},
		{Path: "DestinationConfig.OnFailure.Destination", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^$|kafka://([^.]([a-zA-Z0-9\-_.]{0,248}))|arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1})?:(\d{12})?:(.*)$`)},
		{Path: "DestinationConfig.OnSuccess.Destination", Kind: modelcheck.KindLength, Min: 0, Max: 350},
		{Path: "DestinationConfig.OnSuccess.Destination", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^$|kafka://([^.]([a-zA-Z0-9\-_.]{0,248}))|arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1})?:(\d{12})?:(.*)$`)},
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "MaximumEventAgeInSeconds", Kind: modelcheck.KindRange, Min: 60, Max: 21600},
		{Path: "MaximumRetryAttempts", Kind: modelcheck.KindRange, Min: 0, Max: 2},
		{Path: "Qualifier", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Qualifier", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^\$(LATEST(\.PUBLISHED)?)|[a-zA-Z0-9-_$]+$`)},
	},
	"RemovePermission": {
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "Qualifier", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Qualifier", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^\$(LATEST(\.PUBLISHED)?)|[a-zA-Z0-9-_$]+$`)},
		{Path: "StatementId", Kind: modelcheck.KindLength, Min: 1, Max: 100},
		{Path: "StatementId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^([a-zA-Z0-9-_.]+)$`)},
		{Path: "StatementId", Kind: modelcheck.KindRequired},
	},
	"TagResource": {
		{Path: "Resource", Kind: modelcheck.KindLength, Min: 1, Max: 10000},
		{Path: "Resource", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:(aws[a-zA-Z-]*):lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:(function:[a-zA-Z0-9-_]+(:(\$LATEST|[a-zA-Z0-9-_]+))?|code-signing-config:csc-[a-z0-9]{17}|event-source-mapping:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|(capacity-provider|network-connector):[a-zA-Z0-9-_]{1,64})$`)},
		{Path: "Resource", Kind: modelcheck.KindRequired},
		{Path: "Tags", Kind: modelcheck.KindRequired},
		{Path: "Tags{}", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Tags{}", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$`)},
	},
	"UntagResource": {
		{Path: "Resource", Kind: modelcheck.KindLength, Min: 1, Max: 10000},
		{Path: "Resource", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:(aws[a-zA-Z-]*):lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:(function:[a-zA-Z0-9-_]+(:(\$LATEST|[a-zA-Z0-9-_]+))?|code-signing-config:csc-[a-z0-9]{17}|event-source-mapping:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|(capacity-provider|network-connector):[a-zA-Z0-9-_]{1,64})$`)},
		{Path: "Resource", Kind: modelcheck.KindRequired},
		{Path: "TagKeys", Kind: modelcheck.KindRequired},
		{Path: "TagKeys[]", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "TagKeys[]", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$`)},
	},
	"UpdateEventSourceMapping": {
		{Path: "AmazonManagedKafkaEventSourceConfig.ConsumerGroupId", Kind: modelcheck.KindLength, Min: 1, Max: 200},
		{Path: "AmazonManagedKafkaEventSourceConfig.ConsumerGroupId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ a-zA-Z0-9-\/*:_+=.@-]*$`)},
		{Path: "AmazonManagedKafkaEventSourceConfig.SchemaRegistryConfig.EventRecordFormat", Kind: modelcheck.KindEnum, Enum: []string{"JSON", "SOURCE"}},
		{Path: "AmazonManagedKafkaEventSourceConfig.SchemaRegistryConfig.SchemaRegistryURI", Kind: modelcheck.KindLength, Min: 1, Max: 10000},
		{Path: "AmazonManagedKafkaEventSourceConfig.SchemaRegistryConfig.SchemaRegistryURI", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9-\/*:_+=.@-]*$`)},
		{Path: "BatchSize", Kind: modelcheck.KindRange, Min: 1, Max: 10000},
		{Path: "DestinationConfig.OnFailure.Destination", Kind: modelcheck.KindLength, Min: 0, Max: 350},
		{Path: "DestinationConfig.OnFailure.Destination", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^$|kafka://([^.]([a-zA-Z0-9\-_.]{0,248}))|arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1})?:(\d{12})?:(.*)$`)},
		{Path: "DestinationConfig.OnSuccess.Destination", Kind: modelcheck.KindLength, Min: 0, Max: 350},
		{Path: "DestinationConfig.OnSuccess.Destination", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^$|kafka://([^.]([a-zA-Z0-9\-_.]{0,248}))|arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1})?:(\d{12})?:(.*)$`)},
		{Path: "DocumentDBEventSourceConfig.CollectionName", Kind: modelcheck.KindLength, Min: 1, Max: 57},
		{Path: "DocumentDBEventSourceConfig.DatabaseName", Kind: modelcheck.KindLength, Min: 1, Max: 63},
		{Path: "DocumentDBEventSourceConfig.DatabaseName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[^ /\.$\x22]*$`)},
		{Path: "DocumentDBEventSourceConfig.FullDocument", Kind: modelcheck.KindEnum, Enum: []string{"UpdateLookup", "Default"}},
		{Path: "FilterCriteria.Filters[].Pattern", Kind: modelcheck.KindLength, Min: 0, Max: 4096},
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionResponseTypes[]", Kind: modelcheck.KindEnum, Enum: []string{"ReportBatchItemFailures"}},
		{Path: "KMSKeyArn", Kind: modelcheck.KindLength, Min: 0, Max: 10000},
		{Path: "LoggingConfig.SystemLogLevel", Kind: modelcheck.KindEnum, Enum: []string{"DEBUG", "INFO", "WARN"}},
		{Path: "MaximumBatchingWindowInSeconds", Kind: modelcheck.KindRange, Min: 0, Max: 300},
		{Path: "MaximumRecordAgeInSeconds", Kind: modelcheck.KindRange, Min: -1, Max: 604800},
		{Path: "MaximumRetryAttempts", Kind: modelcheck.KindRange, Min: -1, Max: 10000},
		{Path: "MetricsConfig.Metrics[]", Kind: modelcheck.KindEnum, Enum: []string{"EventCount", "ErrorCount", "KafkaMetrics"}},
		{Path: "ParallelizationFactor", Kind: modelcheck.KindRange, Min: 1, Max: 10},
		{Path: "ProvisionedPollerConfig.MaximumPollers", Kind: modelcheck.KindRange, Min: 1, Max: 10000},
		{Path: "ProvisionedPollerConfig.MinimumPollers", Kind: modelcheck.KindRange, Min: 1, Max: 200},
		{Path: "ProvisionedPollerConfig.PollerGroupName", Kind: modelcheck.KindLength, Min: 0, Max: 128},
		{Path: "ProvisionedPollerConfig.PollerGroupName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9-_]*$`)},
		{Path: "ScalingConfig.MaximumConcurrency", Kind: modelcheck.KindRange, Min: 2, Max: 1000},
		{Path: "SelfManagedKafkaEventSourceConfig.ConsumerGroupId", Kind: modelcheck.KindLength, Min: 1, Max: 200},
		{Path: "SelfManagedKafkaEventSourceConfig.ConsumerGroupId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ a-zA-Z0-9-\/*:_+=.@-]*$`)},
		{Path: "SelfManagedKafkaEventSourceConfig.SchemaRegistryConfig.EventRecordFormat", Kind: modelcheck.KindEnum, Enum: []string{"JSON", "SOURCE"}},
		{Path: "SelfManagedKafkaEventSourceConfig.SchemaRegistryConfig.SchemaRegistryURI", Kind: modelcheck.KindLength, Min: 1, Max: 10000},
		{Path: "SelfManagedKafkaEventSourceConfig.SchemaRegistryConfig.SchemaRegistryURI", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9-\/*:_+=.@-]*$`)},
		{Path: "SourceAccessConfigurations[].Type", Kind: modelcheck.KindEnum, Enum: []string{"VPC_SECURITY_GROUP", "SASL_SCRAM_512_AUTH", "SASL_SCRAM_256_AUTH", "VIRTUAL_HOST", "CLIENT_CERTIFICATE_TLS_AUTH", "SERVER_ROOT_CA_CERTIFICATE", "BASIC_AUTH", "VPC_SUBNET"}},
		{Path: "SourceAccessConfigurations[].URI", Kind: modelcheck.KindLength, Min: 1, Max: 200},
		{Path: "SourceAccessConfigurations[].URI", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ a-zA-Z0-9-\/*:_+=.@-]*$`)},
		{Path: "TumblingWindowInSeconds", Kind: modelcheck.KindRange, Min: 0, Max: 900},
		{Path: "UUID", Kind: modelcheck.KindLength, Min: 36, Max: 36},
		{Path: "UUID", Kind: modelcheck.KindRequired},
	},
	"UpdateFunctionCode": {
		{Path: "Architectures[]", Kind: modelcheck.KindEnum, Enum: []string{"x86_64", "arm64"}},
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:)?((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "PublishTo", Kind: modelcheck.KindEnum, Enum: []string{"LATEST_PUBLISHED"}},
		{Path: "S3Bucket", Kind: modelcheck.KindLength, Min: 3, Max: 63},
		{Path: "S3Key", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "S3Key", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^.*$`)},
		{Path: "S3ObjectStorageMode", Kind: modelcheck.KindEnum, Enum: []string{"COPY", "REFERENCE"}},
		{Path: "S3ObjectVersion", Kind: modelcheck.KindLength, Min: 1, Max: 1024},
		{Path: "S3ObjectVersion", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^.*$`)},
		{Path: "SourceKMSKeyArn", Kind: modelcheck.KindLength, Min: 0, Max: 10000},
	},
	"UpdateFunctionConfiguration": {
		{Path: "CapacityProviderConfig.LambdaManagedInstancesCapacityProviderConfig", Kind: modelcheck.KindRequired},
		{Path: "CapacityProviderConfig.LambdaManagedInstancesCapacityProviderConfig.CapacityProviderArn", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "CapacityProviderConfig.LambdaManagedInstancesCapacityProviderConfig.CapacityProviderArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws[a-zA-Z-]*:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:capacity-provider:[a-zA-Z0-9-_]+$`)},
		{Path: "CapacityProviderConfig.LambdaManagedInstancesCapacityProviderConfig.CapacityProviderArn", Kind: modelcheck.KindRequired},
		{Path: "CapacityProviderConfig.LambdaManagedInstancesCapacityProviderConfig.ExecutionEnvironmentMemoryGiBPerVCpu", Kind: modelcheck.KindRange, Min: 2, Max: 8},
		{Path: "CapacityProviderConfig.LambdaManagedInstancesCapacityProviderConfig.PerExecutionEnvironmentMaxConcurrency", Kind: modelcheck.KindRange, Min: 1, Max: 1600},
		{Path: "DeadLetterConfig.TargetArn", Kind: modelcheck.KindLength, Min: 0, Max: 10000},
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "DurableConfig.ExecutionTimeout", Kind: modelcheck.KindRange, Min: 1, Max: 31622400},
		{Path: "DurableConfig.KMSKeyArn", Kind: modelcheck.KindLength, Min: 0, Max: 10000},
		{Path: "DurableConfig.RetentionPeriodInDays", Kind: modelcheck.KindRange, Min: 1, Max: 90},
		{Path: "EphemeralStorage.Size", Kind: modelcheck.KindRange, Min: 512, Max: 10240},
		{Path: "EphemeralStorage.Size", Kind: modelcheck.KindRequired},
		{Path: "FileSystemConfigs[].Arn", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "FileSystemConfigs[].Arn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws[a-zA-Z-]*:elasticfilesystem:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:access-point/fsap-[a-f0-9]{17}$|^arn:aws[-a-z]*:s3files:[0-9a-z-:]+:file-system/fs-[0-9a-f]{17,40}/access-point/fsap-[0-9a-f]{17,40}$`)},
		{Path: "FileSystemConfigs[].Arn", Kind: modelcheck.KindRequired},
		{Path: "FileSystemConfigs[].LocalMountPath", Kind: modelcheck.KindLength, Min: 0, Max: 160},
		{Path: "FileSystemConfigs[].LocalMountPath", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^/mnt/[a-zA-Z0-9-_.]+$`)},
		{Path: "FileSystemConfigs[].LocalMountPath", Kind: modelcheck.KindRequired},
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:)?((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "Handler", Kind: modelcheck.KindLength, Min: 0, Max: 128},
		{Path: "Handler", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[^\s]+$`)},
		{Path: "ImageConfig.WorkingDirectory", Kind: modelcheck.KindLength, Min: 0, Max: 1000},
		{Path: "KMSKeyArn", Kind: modelcheck.KindLength, Min: 0, Max: 10000},
		{Path: "Layers[]", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "Layers[]", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^((arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:layer:[a-zA-Z0-9-_]+:[0-9]+)|(arn:[a-zA-Z0-9-]+:lambda:::awslayer:[a-zA-Z0-9-_]+))$`)},
		{Path: "LoggingConfig.ApplicationLogLevel", Kind: modelcheck.KindEnum, Enum: []string{"TRACE", "DEBUG", "INFO", "WARN", "ERROR", "FATAL"}},
		{Path: "LoggingConfig.LogFormat", Kind: modelcheck.KindEnum, Enum: []string{"JSON", "Text"}},
		{Path: "LoggingConfig.LogGroup", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "LoggingConfig.LogGroup", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_/#A-Za-z0-9]+$`)},
		{Path: "LoggingConfig.SystemLogLevel", Kind: modelcheck.KindEnum, Enum: []string{"DEBUG", "INFO", "WARN"}},
		{Path: "MemorySize", Kind: modelcheck.KindRange, Min: 128, Max: 32768},
		{Path: "Role", Kind: modelcheck.KindLength, Min: 0, Max: 10000},
		{Path: "Role", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$`)},
		{Path: "Runtime", Kind: modelcheck.KindEnum, Enum: []string{"nodejs8.10", "ruby3.2", "python3.14", "nodejs18.x", "dotnet8", "nodejs4.3-edge", "ruby2.7", "ruby3.3", "provided", "nodejs26.x", "nodejs4.3", "nodejs24.x", "java11", "dotnetcore2.0", "go1.x", "python3.15", "java8.al2023", "nodejs10.x", "nodejs22.x", "java17", "python3.8", "dotnet6", "java8", "java21", "python3.9", "dotnetcore2.1", "dotnet10", "provided.al2", "java11.al2023", "java17.al2023", "nodejs", "nodejs6.10", "nodejs12.x", "nodejs20.x", "java8.al2", "python3.6", "python3.13", "python3.12", "nodejs16.x", "java25", "python2.7", "python3.7", "python3.10", "dotnetcore3.1", "ruby2.5", "nodejs14.x", "python3.11", "dotnetcore1.0", "ruby3.4", "ruby4.0", "provided.al2023"}},
		{Path: "SnapStart.ApplyOn", Kind: modelcheck.KindEnum, Enum: []string{"PublishedVersions", "None"}},
		{Path: "Timeout", Kind: modelcheck.KindRange, Min: 1, Max: 5400},
		{Path: "TracingConfig.Mode", Kind: modelcheck.KindEnum, Enum: []string{"Active", "PassThrough"}},
		{Path: "VpcConfig.SecurityGroupIds[]", Kind: modelcheck.KindLength, Min: 0, Max: 1024},
		{Path: "VpcConfig.SecurityGroupIds[]", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^sg-[0-9a-zA-Z]*$`)},
		{Path: "VpcConfig.SubnetIds[]", Kind: modelcheck.KindLength, Min: 0, Max: 1024},
		{Path: "VpcConfig.SubnetIds[]", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^subnet-[0-9a-z]*$`)},
	},
	"UpdateFunctionEventInvokeConfig": {
		{Path: "DestinationConfig.OnFailure.Destination", Kind: modelcheck.KindLength, Min: 0, Max: 350},
		{Path: "DestinationConfig.OnFailure.Destination", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^$|kafka://([^.]([a-zA-Z0-9\-_.]{0,248}))|arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1})?:(\d{12})?:(.*)$`)},
		{Path: "DestinationConfig.OnSuccess.Destination", Kind: modelcheck.KindLength, Min: 0, Max: 350},
		{Path: "DestinationConfig.OnSuccess.Destination", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^$|kafka://([^.]([a-zA-Z0-9\-_.]{0,248}))|arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1})?:(\d{12})?:(.*)$`)},
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "FunctionName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:(aws[a-zA-Z-]*)?:lambda:(eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:|(((eusc-)?[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?))(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST(\.PUBLISHED)?|[a-zA-Z0-9-_]+))?$`)},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "MaximumEventAgeInSeconds", Kind: modelcheck.KindRange, Min: 60, Max: 21600},
		{Path: "MaximumRetryAttempts", Kind: modelcheck.KindRange, Min: 0, Max: 2},
		{Path: "Qualifier", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Qualifier", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^\$(LATEST(\.PUBLISHED)?)|[a-zA-Z0-9-_$]+$`)},
	},
	"UpdateFunctionUrlConfig": {
		{Path: "AuthType", Kind: modelcheck.KindEnum, Enum: []string{"NONE", "AWS_IAM"}},
		{Path: "Cors.AllowHeaders[]", Kind: modelcheck.KindLength, Min: 0, Max: 1024},
		{Path: "Cors.AllowMethods[]", Kind: modelcheck.KindLength, Min: 0, Max: 6},
		{Path: "Cors.AllowOrigins[]", Kind: modelcheck.KindLength, Min: 1, Max: 253},
		{Path: "Cors.ExposeHeaders[]", Kind: modelcheck.KindLength, Min: 0, Max: 1024},
		{Path: "Cors.MaxAge", Kind: modelcheck.KindRange, Min: 0, Max: 86400},
		{Path: "FunctionName", Kind: modelcheck.KindLength, Min: 1, Max: 140},
		{Path: "FunctionName", Kind: modelcheck.KindRequired},
		{Path: "InvokeMode", Kind: modelcheck.KindEnum, Enum: []string{"BUFFERED", "RESPONSE_STREAM"}},
		{Path: "Qualifier", Kind: modelcheck.KindLength, Min: 1, Max: 128},
	},
}