package iam

// IAM's model-derived input validation: the constraint tables, walked by
// internal/modelcheck.
//
// IAM speaks the Query protocol, so the form is un-flattened into the nested
// shape the paths describe (modelcheck.FromQuery) before the walk. Generated
// from AWS's own service model with `dzaudit cases iam`, and replayed case by
// case in iam/rejection_parity_test.go.

import (
	"github.com/doze-dev/doze-aws/internal/modelcheck"
)

var constraintTables = map[string][]modelcheck.Constraint{
	"AddRoleToInstanceProfile": {
		{Path: "InstanceProfileName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "InstanceProfileName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "InstanceProfileName", Kind: modelcheck.KindRequired},
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"AddUserToGroup": {
		{Path: "GroupName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "GroupName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "GroupName", Kind: modelcheck.KindRequired},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
	"AttachGroupPolicy": {
		{Path: "GroupName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "GroupName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "GroupName", Kind: modelcheck.KindRequired},
		{Path: "PolicyArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicyArn", Kind: modelcheck.KindRequired},
	},
	"AttachRolePolicy": {
		{Path: "PolicyArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicyArn", Kind: modelcheck.KindRequired},
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"AttachUserPolicy": {
		{Path: "PolicyArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicyArn", Kind: modelcheck.KindRequired},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
	"CreateAccessKey": {
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
	},
	"CreateAccountAlias": {
		{Path: "AccountAlias", Kind: modelcheck.KindLength, Min: 3, Max: 63},
		{Path: "AccountAlias", Kind: modelcheck.KindRequired},
	},
	"CreateGroup": {
		{Path: "GroupName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "GroupName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "GroupName", Kind: modelcheck.KindRequired},
		{Path: "Path", Kind: modelcheck.KindLength, Min: 1, Max: 512},
	},
	"CreateInstanceProfile": {
		{Path: "InstanceProfileName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "InstanceProfileName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "InstanceProfileName", Kind: modelcheck.KindRequired},
		{Path: "Path", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "Tags[].Key", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Tags[].Key", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]+$`)},
		{Path: "Tags[].Key", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Value", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Tags[].Value", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]*$`)},
		{Path: "Tags[].Value", Kind: modelcheck.KindRequired},
	},
	"CreatePolicy": {
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 1000},
		{Path: "Path", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "Path", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^((/[A-Za-z0-9\.,\+@=_-]+)*)/$`)},
		{Path: "PolicyDocument", Kind: modelcheck.KindLength, Min: 1, Max: 131072},
		{Path: "PolicyDocument", Kind: modelcheck.KindRequired},
		{Path: "PolicyName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "PolicyName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "PolicyName", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Key", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Tags[].Key", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]+$`)},
		{Path: "Tags[].Key", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Value", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Tags[].Value", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]*$`)},
		{Path: "Tags[].Value", Kind: modelcheck.KindRequired},
	},
	"CreatePolicyVersion": {
		{Path: "PolicyArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicyArn", Kind: modelcheck.KindRequired},
		{Path: "PolicyDocument", Kind: modelcheck.KindLength, Min: 1, Max: 131072},
		{Path: "PolicyDocument", Kind: modelcheck.KindRequired},
	},
	"CreateRole": {
		{Path: "AssumeRolePolicyDocument", Kind: modelcheck.KindLength, Min: 1, Max: 131072},
		{Path: "AssumeRolePolicyDocument", Kind: modelcheck.KindRequired},
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 1000},
		{Path: "MaxSessionDuration", Kind: modelcheck.KindRange, Min: 3600, Max: 43200},
		{Path: "Path", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "PermissionsBoundary", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Key", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Tags[].Key", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]+$`)},
		{Path: "Tags[].Key", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Value", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Tags[].Value", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]*$`)},
		{Path: "Tags[].Value", Kind: modelcheck.KindRequired},
	},
	"CreateServiceLinkedRole": {
		{Path: "AWSServiceName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "AWSServiceName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "AWSServiceName", Kind: modelcheck.KindRequired},
		{Path: "CustomSuffix", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "CustomSuffix", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 1000},
	},
	"CreateUser": {
		{Path: "Path", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "PermissionsBoundary", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "Tags[].Key", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Tags[].Key", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]+$`)},
		{Path: "Tags[].Key", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Value", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Tags[].Value", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]*$`)},
		{Path: "Tags[].Value", Kind: modelcheck.KindRequired},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
	"DeleteAccessKey": {
		{Path: "AccessKeyId", Kind: modelcheck.KindLength, Min: 16, Max: 128},
		{Path: "AccessKeyId", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w]+$`)},
		{Path: "AccessKeyId", Kind: modelcheck.KindRequired},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
	},
	"DeleteAccountAlias": {
		{Path: "AccountAlias", Kind: modelcheck.KindLength, Min: 3, Max: 63},
		{Path: "AccountAlias", Kind: modelcheck.KindRequired},
	},
	"DeleteGroup": {
		{Path: "GroupName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "GroupName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "GroupName", Kind: modelcheck.KindRequired},
	},
	"DeleteGroupPolicy": {
		{Path: "GroupName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "GroupName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "GroupName", Kind: modelcheck.KindRequired},
		{Path: "PolicyName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "PolicyName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "PolicyName", Kind: modelcheck.KindRequired},
	},
	"DeleteInstanceProfile": {
		{Path: "InstanceProfileName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "InstanceProfileName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "InstanceProfileName", Kind: modelcheck.KindRequired},
	},
	"DeletePolicy": {
		{Path: "PolicyArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicyArn", Kind: modelcheck.KindRequired},
	},
	"DeletePolicyVersion": {
		{Path: "PolicyArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicyArn", Kind: modelcheck.KindRequired},
		{Path: "VersionId", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^v[1-9][0-9]*(\.[A-Za-z0-9-]*)?$`)},
		{Path: "VersionId", Kind: modelcheck.KindRequired},
	},
	"DeleteRole": {
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"DeleteRolePermissionsBoundary": {
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"DeleteRolePolicy": {
		{Path: "PolicyName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "PolicyName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "PolicyName", Kind: modelcheck.KindRequired},
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"DeleteServiceLinkedRole": {
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"DeleteUser": {
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
	"DeleteUserPermissionsBoundary": {
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
	"DeleteUserPolicy": {
		{Path: "PolicyName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "PolicyName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "PolicyName", Kind: modelcheck.KindRequired},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
	"DetachGroupPolicy": {
		{Path: "GroupName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "GroupName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "GroupName", Kind: modelcheck.KindRequired},
		{Path: "PolicyArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicyArn", Kind: modelcheck.KindRequired},
	},
	"DetachRolePolicy": {
		{Path: "PolicyArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicyArn", Kind: modelcheck.KindRequired},
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"DetachUserPolicy": {
		{Path: "PolicyArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicyArn", Kind: modelcheck.KindRequired},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
	"GetAccessKeyLastUsed": {
		{Path: "AccessKeyId", Kind: modelcheck.KindLength, Min: 16, Max: 128},
		{Path: "AccessKeyId", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w]+$`)},
		{Path: "AccessKeyId", Kind: modelcheck.KindRequired},
	},
	"GetAccountAuthorizationDetails": {
		{Path: "Filter[]", Kind: modelcheck.KindEnum, Enum: []string{"LocalManagedPolicy", "AWSManagedPolicy", "User", "Role", "Group"}},
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
	},
	"GetContextKeysForCustomPolicy": {
		{Path: "PolicyInputList", Kind: modelcheck.KindRequired},
		{Path: "PolicyInputList[]", Kind: modelcheck.KindLength, Min: 1, Max: 131072},
	},
	"GetContextKeysForPrincipalPolicy": {
		{Path: "PolicyInputList[]", Kind: modelcheck.KindLength, Min: 1, Max: 131072},
		{Path: "PolicySourceArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicySourceArn", Kind: modelcheck.KindRequired},
	},
	"GetGroup": {
		{Path: "GroupName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "GroupName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "GroupName", Kind: modelcheck.KindRequired},
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
	},
	"GetGroupPolicy": {
		{Path: "GroupName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "GroupName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "GroupName", Kind: modelcheck.KindRequired},
		{Path: "PolicyName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "PolicyName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "PolicyName", Kind: modelcheck.KindRequired},
	},
	"GetInstanceProfile": {
		{Path: "InstanceProfileName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "InstanceProfileName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "InstanceProfileName", Kind: modelcheck.KindRequired},
	},
	"GetPolicy": {
		{Path: "PolicyArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicyArn", Kind: modelcheck.KindRequired},
	},
	"GetPolicyVersion": {
		{Path: "PolicyArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicyArn", Kind: modelcheck.KindRequired},
		{Path: "VersionId", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^v[1-9][0-9]*(\.[A-Za-z0-9-]*)?$`)},
		{Path: "VersionId", Kind: modelcheck.KindRequired},
	},
	"GetRole": {
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"GetRolePolicy": {
		{Path: "PolicyName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "PolicyName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "PolicyName", Kind: modelcheck.KindRequired},
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"GetUser": {
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
	},
	"GetUserPolicy": {
		{Path: "PolicyName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "PolicyName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "PolicyName", Kind: modelcheck.KindRequired},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
	"ListAccessKeys": {
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
	},
	"ListAccountAliases": {
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
	},
	"ListAttachedGroupPolicies": {
		{Path: "GroupName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "GroupName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "GroupName", Kind: modelcheck.KindRequired},
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "PathPrefix", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "PathPrefix", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^((/[A-Za-z0-9\.,\+@=_-]+)*)/$`)},
	},
	"ListAttachedRolePolicies": {
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "PathPrefix", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "PathPrefix", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^((/[A-Za-z0-9\.,\+@=_-]+)*)/$`)},
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"ListAttachedUserPolicies": {
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "PathPrefix", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "PathPrefix", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^((/[A-Za-z0-9\.,\+@=_-]+)*)/$`)},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
	"ListEntitiesForPolicy": {
		{Path: "EntityFilter", Kind: modelcheck.KindEnum, Enum: []string{"User", "Role", "Group", "LocalManagedPolicy", "AWSManagedPolicy"}},
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "PathPrefix", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "PolicyArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicyArn", Kind: modelcheck.KindRequired},
		{Path: "PolicyUsageFilter", Kind: modelcheck.KindEnum, Enum: []string{"PermissionsBoundary", "PermissionsPolicy"}},
	},
	"ListGroupPolicies": {
		{Path: "GroupName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "GroupName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "GroupName", Kind: modelcheck.KindRequired},
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
	},
	"ListGroups": {
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "PathPrefix", Kind: modelcheck.KindLength, Min: 1, Max: 512},
	},
	"ListGroupsForUser": {
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
	"ListInstanceProfileTags": {
		{Path: "InstanceProfileName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "InstanceProfileName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "InstanceProfileName", Kind: modelcheck.KindRequired},
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
	},
	"ListInstanceProfiles": {
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "PathPrefix", Kind: modelcheck.KindLength, Min: 1, Max: 512},
	},
	"ListInstanceProfilesForRole": {
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"ListPolicies": {
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "PathPrefix", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "PathPrefix", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^((/[A-Za-z0-9\.,\+@=_-]+)*)/$`)},
		{Path: "PolicyUsageFilter", Kind: modelcheck.KindEnum, Enum: []string{"PermissionsPolicy", "PermissionsBoundary"}},
		{Path: "Scope", Kind: modelcheck.KindEnum, Enum: []string{"All", "AWS", "Local"}},
	},
	"ListPolicyTags": {
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "PolicyArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicyArn", Kind: modelcheck.KindRequired},
	},
	"ListPolicyVersions": {
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "PolicyArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicyArn", Kind: modelcheck.KindRequired},
	},
	"ListRolePolicies": {
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"ListRoleTags": {
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"ListRoles": {
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "PathPrefix", Kind: modelcheck.KindLength, Min: 1, Max: 512},
	},
	"ListUserPolicies": {
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
	"ListUserTags": {
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
	"ListUsers": {
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "PathPrefix", Kind: modelcheck.KindLength, Min: 1, Max: 512},
	},
	"PutGroupPolicy": {
		{Path: "GroupName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "GroupName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "GroupName", Kind: modelcheck.KindRequired},
		{Path: "PolicyDocument", Kind: modelcheck.KindLength, Min: 1, Max: 131072},
		{Path: "PolicyDocument", Kind: modelcheck.KindRequired},
		{Path: "PolicyName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "PolicyName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "PolicyName", Kind: modelcheck.KindRequired},
	},
	"PutRolePermissionsBoundary": {
		{Path: "PermissionsBoundary", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PermissionsBoundary", Kind: modelcheck.KindRequired},
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"PutRolePolicy": {
		{Path: "PolicyDocument", Kind: modelcheck.KindLength, Min: 1, Max: 131072},
		{Path: "PolicyDocument", Kind: modelcheck.KindRequired},
		{Path: "PolicyName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "PolicyName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "PolicyName", Kind: modelcheck.KindRequired},
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"PutUserPermissionsBoundary": {
		{Path: "PermissionsBoundary", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PermissionsBoundary", Kind: modelcheck.KindRequired},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
	"PutUserPolicy": {
		{Path: "PolicyDocument", Kind: modelcheck.KindLength, Min: 1, Max: 131072},
		{Path: "PolicyDocument", Kind: modelcheck.KindRequired},
		{Path: "PolicyName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "PolicyName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "PolicyName", Kind: modelcheck.KindRequired},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
	"RemoveRoleFromInstanceProfile": {
		{Path: "InstanceProfileName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "InstanceProfileName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "InstanceProfileName", Kind: modelcheck.KindRequired},
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"RemoveUserFromGroup": {
		{Path: "GroupName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "GroupName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "GroupName", Kind: modelcheck.KindRequired},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
	"SetDefaultPolicyVersion": {
		{Path: "PolicyArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicyArn", Kind: modelcheck.KindRequired},
		{Path: "VersionId", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^v[1-9][0-9]*(\.[A-Za-z0-9-]*)?$`)},
		{Path: "VersionId", Kind: modelcheck.KindRequired},
	},
	"SimulateCustomPolicy": {
		{Path: "ActionNames", Kind: modelcheck.KindRequired},
		{Path: "ActionNames[]", Kind: modelcheck.KindLength, Min: 3, Max: 128},
		{Path: "CallerArn", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "ContextEntries[].ContextKeyName", Kind: modelcheck.KindLength, Min: 5, Max: 256},
		{Path: "ContextEntries[].ContextKeyType", Kind: modelcheck.KindEnum, Enum: []string{"string", "stringList", "numeric", "boolean", "booleanList", "ip", "date", "numericList", "ipList", "binary", "binaryList", "dateList"}},
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "OrderedOrganizationPolicyInputList[].ServiceControlPolicyInputList[]", Kind: modelcheck.KindLength, Min: 1, Max: 131072},
		{Path: "PermissionsBoundaryPolicyInputList[]", Kind: modelcheck.KindLength, Min: 1, Max: 131072},
		{Path: "PolicyInputList", Kind: modelcheck.KindRequired},
		{Path: "PolicyInputList[]", Kind: modelcheck.KindLength, Min: 1, Max: 131072},
		{Path: "ResourceArns[]", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "ResourceHandlingOption", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "ResourceOwner", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "ResourcePolicy", Kind: modelcheck.KindLength, Min: 1, Max: 131072},
	},
	"SimulatePrincipalPolicy": {
		{Path: "ActionNames", Kind: modelcheck.KindRequired},
		{Path: "ActionNames[]", Kind: modelcheck.KindLength, Min: 3, Max: 128},
		{Path: "CallerArn", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "ContextEntries[].ContextKeyName", Kind: modelcheck.KindLength, Min: 5, Max: 256},
		{Path: "ContextEntries[].ContextKeyType", Kind: modelcheck.KindEnum, Enum: []string{"dateList", "string", "stringList", "numeric", "boolean", "booleanList", "ip", "date", "numericList", "ipList", "binary", "binaryList"}},
		{Path: "Marker", Kind: modelcheck.KindLength, Min: 1, Max: 320},
		{Path: "MaxItems", Kind: modelcheck.KindRange, Min: 1, Max: 1000},
		{Path: "PermissionsBoundaryPolicyInputList[]", Kind: modelcheck.KindLength, Min: 1, Max: 131072},
		{Path: "PolicyInputList[]", Kind: modelcheck.KindLength, Min: 1, Max: 131072},
		{Path: "PolicySourceArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicySourceArn", Kind: modelcheck.KindRequired},
		{Path: "ResourceArns[]", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "ResourceHandlingOption", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "ResourceOwner", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "ResourcePolicy", Kind: modelcheck.KindLength, Min: 1, Max: 131072},
	},
	"TagInstanceProfile": {
		{Path: "InstanceProfileName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "InstanceProfileName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "InstanceProfileName", Kind: modelcheck.KindRequired},
		{Path: "Tags", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Key", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Tags[].Key", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]+$`)},
		{Path: "Tags[].Key", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Value", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Tags[].Value", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]*$`)},
		{Path: "Tags[].Value", Kind: modelcheck.KindRequired},
	},
	"TagPolicy": {
		{Path: "PolicyArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicyArn", Kind: modelcheck.KindRequired},
		{Path: "Tags", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Key", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Tags[].Key", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]+$`)},
		{Path: "Tags[].Key", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Value", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Tags[].Value", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]*$`)},
		{Path: "Tags[].Value", Kind: modelcheck.KindRequired},
	},
	"TagRole": {
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
		{Path: "Tags", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Key", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Tags[].Key", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]+$`)},
		{Path: "Tags[].Key", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Value", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Tags[].Value", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]*$`)},
		{Path: "Tags[].Value", Kind: modelcheck.KindRequired},
	},
	"TagUser": {
		{Path: "Tags", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Key", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Tags[].Key", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]+$`)},
		{Path: "Tags[].Key", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Value", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Tags[].Value", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]*$`)},
		{Path: "Tags[].Value", Kind: modelcheck.KindRequired},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
	"UntagInstanceProfile": {
		{Path: "InstanceProfileName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "InstanceProfileName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "InstanceProfileName", Kind: modelcheck.KindRequired},
		{Path: "TagKeys", Kind: modelcheck.KindRequired},
		{Path: "TagKeys[]", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "TagKeys[]", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]+$`)},
	},
	"UntagPolicy": {
		{Path: "PolicyArn", Kind: modelcheck.KindLength, Min: 20, Max: 2048},
		{Path: "PolicyArn", Kind: modelcheck.KindRequired},
		{Path: "TagKeys", Kind: modelcheck.KindRequired},
		{Path: "TagKeys[]", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "TagKeys[]", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]+$`)},
	},
	"UntagRole": {
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
		{Path: "TagKeys", Kind: modelcheck.KindRequired},
		{Path: "TagKeys[]", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "TagKeys[]", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]+$`)},
	},
	"UntagUser": {
		{Path: "TagKeys", Kind: modelcheck.KindRequired},
		{Path: "TagKeys[]", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "TagKeys[]", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\p{L}\p{Z}\p{N}_.:/=+\-@]+$`)},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
	"UpdateAccessKey": {
		{Path: "AccessKeyId", Kind: modelcheck.KindLength, Min: 16, Max: 128},
		{Path: "AccessKeyId", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w]+$`)},
		{Path: "AccessKeyId", Kind: modelcheck.KindRequired},
		{Path: "Status", Kind: modelcheck.KindEnum, Enum: []string{"Active", "Inactive", "Expired"}},
		{Path: "Status", Kind: modelcheck.KindRequired},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
	},
	"UpdateAssumeRolePolicy": {
		{Path: "PolicyDocument", Kind: modelcheck.KindLength, Min: 1, Max: 131072},
		{Path: "PolicyDocument", Kind: modelcheck.KindRequired},
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"UpdateGroup": {
		{Path: "GroupName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "GroupName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "GroupName", Kind: modelcheck.KindRequired},
		{Path: "NewGroupName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "NewGroupName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "NewPath", Kind: modelcheck.KindLength, Min: 1, Max: 512},
	},
	"UpdateRole": {
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 1000},
		{Path: "MaxSessionDuration", Kind: modelcheck.KindRange, Min: 3600, Max: 43200},
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"UpdateRoleDescription": {
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 1000},
		{Path: "Description", Kind: modelcheck.KindRequired},
		{Path: "RoleName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "RoleName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "RoleName", Kind: modelcheck.KindRequired},
	},
	"UpdateUser": {
		{Path: "NewPath", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "NewUserName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "NewUserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "UserName", Kind: modelcheck.KindPattern, Pat: modelcheck.Pattern(`^[\w+=,.@-]+$`)},
		{Path: "UserName", Kind: modelcheck.KindRequired},
	},
}
