package eventbridge

// EventBridge's model-derived input validation: the constraint tables, walked
// by internal/modelcheck.
//
// Generated with `dzaudit cases eventbridge` rather than transcribed, and
// replayed case by case in eventbridge/rejection_parity_test.go.

import (
	"regexp"

	"github.com/doze-dev/doze-aws/internal/modelcheck"
)

var constraintTables = map[string][]modelcheck.Constraint{
	"CancelReplay": {
		{Path: "ReplayName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "ReplayName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "ReplayName", Kind: modelcheck.KindRequired},
	},
	"CreateApiDestination": {
		{Path: "ConnectionArn", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "ConnectionArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws([a-z]|\-)*:events:([a-z]|\d|\-)*:([0-9]{12})?:connection\/[\.\-_A-Za-z0-9]+\/[\-A-Za-z0-9]+$`)},
		{Path: "ConnectionArn", Kind: modelcheck.KindRequired},
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 512},
		{Path: "HttpMethod", Kind: modelcheck.KindRequired},
		{Path: "HttpMethod", Kind: modelcheck.KindEnum, Enum: []string{"HEAD", "OPTIONS", "PUT", "PATCH", "DELETE", "POST", "GET"}},
		{Path: "InvocationEndpoint", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "InvocationEndpoint", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^((%[0-9A-Fa-f]{2}|[-()_.!~*';/?:@\x26=+$,A-Za-z0-9])+)([).!';/?:,])?$`)},
		{Path: "InvocationEndpoint", Kind: modelcheck.KindRequired},
		{Path: "InvocationRateLimitPerSecond", Kind: modelcheck.KindRange, Min: 1, Max: modelcheck.NoMax},
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindRequired},
	},
	"CreateArchive": {
		{Path: "ArchiveName", Kind: modelcheck.KindLength, Min: 1, Max: 48},
		{Path: "ArchiveName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "ArchiveName", Kind: modelcheck.KindRequired},
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 512},
		{Path: "EventPattern", Kind: modelcheck.KindLength, Min: 0, Max: 4096},
		{Path: "EventSourceArn", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "EventSourceArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws([a-z]|\-)*:events:([a-z]|\d|\-)*:([0-9]{12})?:.+\/.+$`)},
		{Path: "EventSourceArn", Kind: modelcheck.KindRequired},
		{Path: "KmsKeyIdentifier", Kind: modelcheck.KindLength, Min: 0, Max: 2048},
		{Path: "KmsKeyIdentifier", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_\-/:]*$`)},
		{Path: "RetentionDays", Kind: modelcheck.KindRange, Min: 0, Max: modelcheck.NoMax},
	},
	"CreateConnection": {
		{Path: "AuthorizationType", Kind: modelcheck.KindRequired},
		{Path: "AuthorizationType", Kind: modelcheck.KindEnum, Enum: []string{"API_KEY", "BASIC", "OAUTH_CLIENT_CREDENTIALS"}},
		{Path: "AuthParameters", Kind: modelcheck.KindRequired},
		{Path: "AuthParameters.ApiKeyAuthParameters.ApiKeyName", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "AuthParameters.ApiKeyAuthParameters.ApiKeyName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ \t]*[^\x00-\x1F:\x7F]+([ \t]+[^\x00-\x1F:\x7F]+)*[ \t]*$`)},
		{Path: "AuthParameters.ApiKeyAuthParameters.ApiKeyName", Kind: modelcheck.KindRequired},
		{Path: "AuthParameters.ApiKeyAuthParameters.ApiKeyValue", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "AuthParameters.ApiKeyAuthParameters.ApiKeyValue", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ \t]*[^\x00-\x1F:\x7F]+([ \t]+[^\x00-\x1F:\x7F]+)*[ \t]*$`)},
		{Path: "AuthParameters.ApiKeyAuthParameters.ApiKeyValue", Kind: modelcheck.KindRequired},
		{Path: "AuthParameters.BasicAuthParameters.Password", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "AuthParameters.BasicAuthParameters.Password", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ \t]*[^\x00-\x1F:\x7F]+([ \t]+[^\x00-\x1F:\x7F]+)*[ \t]*$`)},
		{Path: "AuthParameters.BasicAuthParameters.Password", Kind: modelcheck.KindRequired},
		{Path: "AuthParameters.BasicAuthParameters.Username", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "AuthParameters.BasicAuthParameters.Username", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ \t]*[^\x00-\x1F:\x7F]+([ \t]+[^\x00-\x1F:\x7F]+)*[ \t]*$`)},
		{Path: "AuthParameters.BasicAuthParameters.Username", Kind: modelcheck.KindRequired},
		{Path: "AuthParameters.ConnectivityParameters.ResourceParameters", Kind: modelcheck.KindRequired},
		{Path: "AuthParameters.ConnectivityParameters.ResourceParameters.ResourceConfigurationArn", Kind: modelcheck.KindLength, Min: 0, Max: 2048},
		{Path: "AuthParameters.ConnectivityParameters.ResourceParameters.ResourceConfigurationArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(?:^arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:resourceconfiguration/rcfg-[0-9a-z]{17}$|^$)$`)},
		{Path: "AuthParameters.ConnectivityParameters.ResourceParameters.ResourceConfigurationArn", Kind: modelcheck.KindRequired},
		{Path: "AuthParameters.OAuthParameters.AuthorizationEndpoint", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "AuthParameters.OAuthParameters.AuthorizationEndpoint", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^((%[0-9A-Fa-f]{2}|[-()_.!~*';/?:@\x26=+$,A-Za-z0-9])+)([).!';/?:,])?$`)},
		{Path: "AuthParameters.OAuthParameters.AuthorizationEndpoint", Kind: modelcheck.KindRequired},
		{Path: "AuthParameters.OAuthParameters.ClientParameters", Kind: modelcheck.KindRequired},
		{Path: "AuthParameters.OAuthParameters.ClientParameters.ClientID", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "AuthParameters.OAuthParameters.ClientParameters.ClientID", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ \t]*[^\x00-\x1F:\x7F]+([ \t]+[^\x00-\x1F:\x7F]+)*[ \t]*$`)},
		{Path: "AuthParameters.OAuthParameters.ClientParameters.ClientID", Kind: modelcheck.KindRequired},
		{Path: "AuthParameters.OAuthParameters.ClientParameters.ClientSecret", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "AuthParameters.OAuthParameters.ClientParameters.ClientSecret", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ \t]*[^\x00-\x1F:\x7F]+([ \t]+[^\x00-\x1F:\x7F]+)*[ \t]*$`)},
		{Path: "AuthParameters.OAuthParameters.ClientParameters.ClientSecret", Kind: modelcheck.KindRequired},
		{Path: "AuthParameters.OAuthParameters.HttpMethod", Kind: modelcheck.KindRequired},
		{Path: "AuthParameters.OAuthParameters.HttpMethod", Kind: modelcheck.KindEnum, Enum: []string{"GET", "POST", "PUT"}},
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 512},
		{Path: "InvocationConnectivityParameters.ResourceParameters", Kind: modelcheck.KindRequired},
		{Path: "InvocationConnectivityParameters.ResourceParameters.ResourceConfigurationArn", Kind: modelcheck.KindLength, Min: 0, Max: 2048},
		{Path: "InvocationConnectivityParameters.ResourceParameters.ResourceConfigurationArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(?:^arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:resourceconfiguration/rcfg-[0-9a-z]{17}$|^$)$`)},
		{Path: "InvocationConnectivityParameters.ResourceParameters.ResourceConfigurationArn", Kind: modelcheck.KindRequired},
		{Path: "KmsKeyIdentifier", Kind: modelcheck.KindLength, Min: 0, Max: 2048},
		{Path: "KmsKeyIdentifier", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_\-/:]*$`)},
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindRequired},
	},
	"CreateEventBus": {
		{Path: "DeadLetterConfig.Arn", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 512},
		{Path: "EventSourceName", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "EventSourceName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^aws\.partner(/[\.\-_A-Za-z0-9]+){2,}$`)},
		{Path: "KmsKeyIdentifier", Kind: modelcheck.KindLength, Min: 0, Max: 2048},
		{Path: "KmsKeyIdentifier", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_\-/:]*$`)},
		{Path: "LogConfig.IncludeDetail", Kind: modelcheck.KindEnum, Enum: []string{"NONE", "FULL"}},
		{Path: "LogConfig.Level", Kind: modelcheck.KindEnum, Enum: []string{"OFF", "ERROR", "INFO", "TRACE"}},
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[/\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Key", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Tags[].Key", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Value", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Tags[].Value", Kind: modelcheck.KindRequired},
	},
	"DeauthorizeConnection": {
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindRequired},
	},
	"DeleteApiDestination": {
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindRequired},
	},
	"DeleteArchive": {
		{Path: "ArchiveName", Kind: modelcheck.KindLength, Min: 1, Max: 48},
		{Path: "ArchiveName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "ArchiveName", Kind: modelcheck.KindRequired},
	},
	"DeleteConnection": {
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindRequired},
	},
	"DeleteEventBus": {
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[/\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindRequired},
	},
	"DeleteRule": {
		{Path: "EventBusName", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "EventBusName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:aws[\w-]*:events:[a-z]+-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[/\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindRequired},
	},
	"DescribeApiDestination": {
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindRequired},
	},
	"DescribeArchive": {
		{Path: "ArchiveName", Kind: modelcheck.KindLength, Min: 1, Max: 48},
		{Path: "ArchiveName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "ArchiveName", Kind: modelcheck.KindRequired},
	},
	"DescribeConnection": {
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindRequired},
	},
	"DescribeEventBus": {
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:aws[\w-]*:events:[a-z]+-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[/\.\-_A-Za-z0-9]+$`)},
	},
	"DescribeReplay": {
		{Path: "ReplayName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "ReplayName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "ReplayName", Kind: modelcheck.KindRequired},
	},
	"DescribeRule": {
		{Path: "EventBusName", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "EventBusName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:aws[\w-]*:events:[a-z]+-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[/\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindRequired},
	},
	"DisableRule": {
		{Path: "EventBusName", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "EventBusName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:aws[\w-]*:events:[a-z]+-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[/\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindRequired},
	},
	"EnableRule": {
		{Path: "EventBusName", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "EventBusName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:aws[\w-]*:events:[a-z]+-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[/\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindRequired},
	},
	"ListApiDestinations": {
		{Path: "ConnectionArn", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "ConnectionArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws([a-z]|\-)*:events:([a-z]|\d|\-)*:([0-9]{12})?:connection\/[\.\-_A-Za-z0-9]+\/[\-A-Za-z0-9]+$`)},
		{Path: "Limit", Kind: modelcheck.KindRange, Min: 1, Max: 100},
		{Path: "NamePrefix", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "NamePrefix", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "NextToken", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
	},
	"ListArchives": {
		{Path: "EventSourceArn", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "EventSourceArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws([a-z]|\-)*:events:([a-z]|\d|\-)*:([0-9]{12})?:.+\/.+$`)},
		{Path: "Limit", Kind: modelcheck.KindRange, Min: 1, Max: 100},
		{Path: "NamePrefix", Kind: modelcheck.KindLength, Min: 1, Max: 48},
		{Path: "NamePrefix", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "NextToken", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "State", Kind: modelcheck.KindEnum, Enum: []string{"CREATE_FAILED", "UPDATE_FAILED", "ENABLED", "DISABLED", "CREATING", "UPDATING"}},
	},
	"ListConnections": {
		{Path: "ConnectionState", Kind: modelcheck.KindEnum, Enum: []string{"UPDATING", "DEAUTHORIZED", "AUTHORIZING", "DEAUTHORIZING", "ACTIVE", "CREATING", "DELETING", "AUTHORIZED", "FAILED_CONNECTIVITY"}},
		{Path: "Limit", Kind: modelcheck.KindRange, Min: 1, Max: 100},
		{Path: "NamePrefix", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "NamePrefix", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "NextToken", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
	},
	"ListEventBuses": {
		{Path: "Limit", Kind: modelcheck.KindRange, Min: 1, Max: 100},
		{Path: "NamePrefix", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "NamePrefix", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[/\.\-_A-Za-z0-9]+$`)},
		{Path: "NextToken", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
	},
	"ListReplays": {
		{Path: "EventSourceArn", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "EventSourceArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws([a-z]|\-)*:events:([a-z]|\d|\-)*:([0-9]{12})?:.+\/.+$`)},
		{Path: "Limit", Kind: modelcheck.KindRange, Min: 1, Max: 100},
		{Path: "NamePrefix", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "NamePrefix", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "NextToken", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "State", Kind: modelcheck.KindEnum, Enum: []string{"STARTING", "RUNNING", "CANCELLING", "COMPLETED", "CANCELLED", "FAILED"}},
	},
	"ListRuleNamesByTarget": {
		{Path: "EventBusName", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "EventBusName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:aws[\w-]*:events:[a-z]+-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[/\.\-_A-Za-z0-9]+$`)},
		{Path: "Limit", Kind: modelcheck.KindRange, Min: 1, Max: 100},
		{Path: "NextToken", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "TargetArn", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "TargetArn", Kind: modelcheck.KindRequired},
	},
	"ListRules": {
		{Path: "EventBusName", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "EventBusName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:aws[\w-]*:events:[a-z]+-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[/\.\-_A-Za-z0-9]+$`)},
		{Path: "Limit", Kind: modelcheck.KindRange, Min: 1, Max: 100},
		{Path: "NamePrefix", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "NamePrefix", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "NextToken", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
	},
	"ListTagsForResource": {
		{Path: "ResourceARN", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "ResourceARN", Kind: modelcheck.KindRequired},
	},
	"ListTargetsByRule": {
		{Path: "EventBusName", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "EventBusName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:aws[\w-]*:events:[a-z]+-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[/\.\-_A-Za-z0-9]+$`)},
		{Path: "Limit", Kind: modelcheck.KindRange, Min: 1, Max: 100},
		{Path: "NextToken", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "Rule", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Rule", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Rule", Kind: modelcheck.KindRequired},
	},
	"PutEvents": {
		{Path: "EndpointId", Kind: modelcheck.KindLength, Min: 1, Max: 50},
		{Path: "EndpointId", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[A-Za-z0-9\-]+[\.][A-Za-z0-9\-]+$`)},
		{Path: "Entries", Kind: modelcheck.KindRequired},
		{Path: "Entries[].EventBusName", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "Entries[].EventBusName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:aws[\w-]*:events:[a-z]+-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[\.\-_A-Za-z0-9]+$`)},
		{Path: "Entries[].Resources[]", Kind: modelcheck.KindLength, Min: 0, Max: 2048},
		{Path: "Entries[].TraceHeader", Kind: modelcheck.KindLength, Min: 1, Max: 500},
	},
	"PutRule": {
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 512},
		{Path: "EventBusName", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "EventBusName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:aws[\w-]*:events:[a-z]+-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[/\.\-_A-Za-z0-9]+$`)},
		{Path: "EventPattern", Kind: modelcheck.KindLength, Min: 0, Max: 4096},
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindRequired},
		{Path: "RoleArn", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "ScheduleExpression", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "State", Kind: modelcheck.KindEnum, Enum: []string{"ENABLED", "DISABLED", "ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS"}},
		{Path: "Tags[].Key", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Tags[].Key", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Value", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Tags[].Value", Kind: modelcheck.KindRequired},
	},
	"PutTargets": {
		{Path: "EventBusName", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "EventBusName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:aws[\w-]*:events:[a-z]+-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[/\.\-_A-Za-z0-9]+$`)},
		{Path: "Rule", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Rule", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Rule", Kind: modelcheck.KindRequired},
		{Path: "Targets", Kind: modelcheck.KindRequired},
		{Path: "Targets[].AppSyncParameters.GraphQLOperation", Kind: modelcheck.KindLength, Min: 1, Max: 1048576},
		{Path: "Targets[].Arn", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "Targets[].Arn", Kind: modelcheck.KindRequired},
		{Path: "Targets[].BatchParameters.JobDefinition", Kind: modelcheck.KindRequired},
		{Path: "Targets[].BatchParameters.JobName", Kind: modelcheck.KindRequired},
		{Path: "Targets[].DeadLetterConfig.Arn", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "Targets[].EcsParameters.LaunchType", Kind: modelcheck.KindEnum, Enum: []string{"EC2", "FARGATE", "EXTERNAL"}},
		{Path: "Targets[].EcsParameters.PropagateTags", Kind: modelcheck.KindEnum, Enum: []string{"TASK_DEFINITION"}},
		{Path: "Targets[].EcsParameters.ReferenceId", Kind: modelcheck.KindLength, Min: 0, Max: 1024},
		{Path: "Targets[].EcsParameters.TaskCount", Kind: modelcheck.KindRange, Min: 1, Max: modelcheck.NoMax},
		{Path: "Targets[].EcsParameters.TaskDefinitionArn", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "Targets[].EcsParameters.TaskDefinitionArn", Kind: modelcheck.KindRequired},
		{Path: "Targets[].Id", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Targets[].Id", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Targets[].Id", Kind: modelcheck.KindRequired},
		{Path: "Targets[].Input", Kind: modelcheck.KindLength, Min: 0, Max: 8192},
		{Path: "Targets[].InputPath", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Targets[].InputTransformer.InputTemplate", Kind: modelcheck.KindLength, Min: 1, Max: 8192},
		{Path: "Targets[].InputTransformer.InputTemplate", Kind: modelcheck.KindRequired},
		{Path: "Targets[].KinesisParameters.PartitionKeyPath", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Targets[].KinesisParameters.PartitionKeyPath", Kind: modelcheck.KindRequired},
		{Path: "Targets[].RedshiftDataParameters.Database", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Targets[].RedshiftDataParameters.Database", Kind: modelcheck.KindRequired},
		{Path: "Targets[].RedshiftDataParameters.DbUser", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Targets[].RedshiftDataParameters.SecretManagerArn", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "Targets[].RedshiftDataParameters.SecretManagerArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(^arn:aws([a-z]|\-)*:secretsmanager:[a-z0-9-.]+:.*)|(\$(\.[\w_-]+(\[(\d+|\*)\])*)*)$`)},
		{Path: "Targets[].RedshiftDataParameters.Sql", Kind: modelcheck.KindLength, Min: 1, Max: 100000},
		{Path: "Targets[].RedshiftDataParameters.StatementName", Kind: modelcheck.KindLength, Min: 1, Max: 500},
		{Path: "Targets[].RetryPolicy.MaximumEventAgeInSeconds", Kind: modelcheck.KindRange, Min: 60, Max: 86400},
		{Path: "Targets[].RetryPolicy.MaximumRetryAttempts", Kind: modelcheck.KindRange, Min: 0, Max: 185},
		{Path: "Targets[].RoleArn", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "Targets[].RunCommandParameters.RunCommandTargets", Kind: modelcheck.KindRequired},
		{Path: "Targets[].SqsParameters.MessageGroupId", Kind: modelcheck.KindLength, Min: 0, Max: 100},
	},
	"RemoveTargets": {
		{Path: "EventBusName", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "EventBusName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(arn:aws[\w-]*:events:[a-z]+-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[/\.\-_A-Za-z0-9]+$`)},
		{Path: "Ids", Kind: modelcheck.KindRequired},
		{Path: "Ids[]", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Ids[]", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Rule", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Rule", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Rule", Kind: modelcheck.KindRequired},
	},
	"StartReplay": {
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 512},
		{Path: "Destination", Kind: modelcheck.KindRequired},
		{Path: "Destination.Arn", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "Destination.Arn", Kind: modelcheck.KindRequired},
		{Path: "Destination.FilterArns[]", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "EventEndTime", Kind: modelcheck.KindRequired},
		{Path: "EventSourceArn", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "EventSourceArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws([a-z]|\-)*:events:([a-z]|\d|\-)*:([0-9]{12})?:.+\/.+$`)},
		{Path: "EventSourceArn", Kind: modelcheck.KindRequired},
		{Path: "EventStartTime", Kind: modelcheck.KindRequired},
		{Path: "ReplayName", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "ReplayName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "ReplayName", Kind: modelcheck.KindRequired},
	},
	"TagResource": {
		{Path: "ResourceARN", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "ResourceARN", Kind: modelcheck.KindRequired},
		{Path: "Tags", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Key", Kind: modelcheck.KindLength, Min: 1, Max: 128},
		{Path: "Tags[].Key", Kind: modelcheck.KindRequired},
		{Path: "Tags[].Value", Kind: modelcheck.KindLength, Min: 0, Max: 256},
		{Path: "Tags[].Value", Kind: modelcheck.KindRequired},
	},
	"TestEventPattern": {
		{Path: "Event", Kind: modelcheck.KindRequired},
		{Path: "EventPattern", Kind: modelcheck.KindLength, Min: 0, Max: 4096},
		{Path: "EventPattern", Kind: modelcheck.KindRequired},
	},
	"UntagResource": {
		{Path: "ResourceARN", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "ResourceARN", Kind: modelcheck.KindRequired},
		{Path: "TagKeys", Kind: modelcheck.KindRequired},
		{Path: "TagKeys[]", Kind: modelcheck.KindLength, Min: 1, Max: 128},
	},
	"UpdateApiDestination": {
		{Path: "ConnectionArn", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "ConnectionArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^arn:aws([a-z]|\-)*:events:([a-z]|\d|\-)*:([0-9]{12})?:connection\/[\.\-_A-Za-z0-9]+\/[\-A-Za-z0-9]+$`)},
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 512},
		{Path: "HttpMethod", Kind: modelcheck.KindEnum, Enum: []string{"DELETE", "POST", "GET", "HEAD", "OPTIONS", "PUT", "PATCH"}},
		{Path: "InvocationEndpoint", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "InvocationEndpoint", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^((%[0-9A-Fa-f]{2}|[-()_.!~*';/?:@\x26=+$,A-Za-z0-9])+)([).!';/?:,])?$`)},
		{Path: "InvocationRateLimitPerSecond", Kind: modelcheck.KindRange, Min: 1, Max: modelcheck.NoMax},
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindRequired},
	},
	"UpdateArchive": {
		{Path: "ArchiveName", Kind: modelcheck.KindLength, Min: 1, Max: 48},
		{Path: "ArchiveName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "ArchiveName", Kind: modelcheck.KindRequired},
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 512},
		{Path: "EventPattern", Kind: modelcheck.KindLength, Min: 0, Max: 4096},
		{Path: "KmsKeyIdentifier", Kind: modelcheck.KindLength, Min: 0, Max: 2048},
		{Path: "KmsKeyIdentifier", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_\-/:]*$`)},
		{Path: "RetentionDays", Kind: modelcheck.KindRange, Min: 0, Max: modelcheck.NoMax},
	},
	"UpdateConnection": {
		{Path: "AuthorizationType", Kind: modelcheck.KindEnum, Enum: []string{"API_KEY", "BASIC", "OAUTH_CLIENT_CREDENTIALS"}},
		{Path: "AuthParameters.ApiKeyAuthParameters.ApiKeyName", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "AuthParameters.ApiKeyAuthParameters.ApiKeyName", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ \t]*[^\x00-\x1F:\x7F]+([ \t]+[^\x00-\x1F:\x7F]+)*[ \t]*$`)},
		{Path: "AuthParameters.ApiKeyAuthParameters.ApiKeyValue", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "AuthParameters.ApiKeyAuthParameters.ApiKeyValue", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ \t]*[^\x00-\x1F:\x7F]+([ \t]+[^\x00-\x1F:\x7F]+)*[ \t]*$`)},
		{Path: "AuthParameters.BasicAuthParameters.Password", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "AuthParameters.BasicAuthParameters.Password", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ \t]*[^\x00-\x1F:\x7F]+([ \t]+[^\x00-\x1F:\x7F]+)*[ \t]*$`)},
		{Path: "AuthParameters.BasicAuthParameters.Username", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "AuthParameters.BasicAuthParameters.Username", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ \t]*[^\x00-\x1F:\x7F]+([ \t]+[^\x00-\x1F:\x7F]+)*[ \t]*$`)},
		{Path: "AuthParameters.ConnectivityParameters.ResourceParameters", Kind: modelcheck.KindRequired},
		{Path: "AuthParameters.ConnectivityParameters.ResourceParameters.ResourceConfigurationArn", Kind: modelcheck.KindLength, Min: 0, Max: 2048},
		{Path: "AuthParameters.ConnectivityParameters.ResourceParameters.ResourceConfigurationArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(?:^arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:resourceconfiguration/rcfg-[0-9a-z]{17}$|^$)$`)},
		{Path: "AuthParameters.ConnectivityParameters.ResourceParameters.ResourceConfigurationArn", Kind: modelcheck.KindRequired},
		{Path: "AuthParameters.OAuthParameters.AuthorizationEndpoint", Kind: modelcheck.KindLength, Min: 1, Max: 2048},
		{Path: "AuthParameters.OAuthParameters.AuthorizationEndpoint", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^((%[0-9A-Fa-f]{2}|[-()_.!~*';/?:@\x26=+$,A-Za-z0-9])+)([).!';/?:,])?$`)},
		{Path: "AuthParameters.OAuthParameters.ClientParameters.ClientID", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "AuthParameters.OAuthParameters.ClientParameters.ClientID", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ \t]*[^\x00-\x1F:\x7F]+([ \t]+[^\x00-\x1F:\x7F]+)*[ \t]*$`)},
		{Path: "AuthParameters.OAuthParameters.ClientParameters.ClientSecret", Kind: modelcheck.KindLength, Min: 1, Max: 512},
		{Path: "AuthParameters.OAuthParameters.ClientParameters.ClientSecret", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[ \t]*[^\x00-\x1F:\x7F]+([ \t]+[^\x00-\x1F:\x7F]+)*[ \t]*$`)},
		{Path: "AuthParameters.OAuthParameters.HttpMethod", Kind: modelcheck.KindEnum, Enum: []string{"POST", "PUT", "GET"}},
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 512},
		{Path: "InvocationConnectivityParameters.ResourceParameters", Kind: modelcheck.KindRequired},
		{Path: "InvocationConnectivityParameters.ResourceParameters.ResourceConfigurationArn", Kind: modelcheck.KindLength, Min: 0, Max: 2048},
		{Path: "InvocationConnectivityParameters.ResourceParameters.ResourceConfigurationArn", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^(?:^arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:resourceconfiguration/rcfg-[0-9a-z]{17}$|^$)$`)},
		{Path: "InvocationConnectivityParameters.ResourceParameters.ResourceConfigurationArn", Kind: modelcheck.KindRequired},
		{Path: "KmsKeyIdentifier", Kind: modelcheck.KindLength, Min: 0, Max: 2048},
		{Path: "KmsKeyIdentifier", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_\-/:]*$`)},
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 64},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[\.\-_A-Za-z0-9]+$`)},
		{Path: "Name", Kind: modelcheck.KindRequired},
	},
	"UpdateEventBus": {
		{Path: "DeadLetterConfig.Arn", Kind: modelcheck.KindLength, Min: 1, Max: 1600},
		{Path: "Description", Kind: modelcheck.KindLength, Min: 0, Max: 512},
		{Path: "KmsKeyIdentifier", Kind: modelcheck.KindLength, Min: 0, Max: 2048},
		{Path: "KmsKeyIdentifier", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[a-zA-Z0-9_\-/:]*$`)},
		{Path: "LogConfig.IncludeDetail", Kind: modelcheck.KindEnum, Enum: []string{"NONE", "FULL"}},
		{Path: "LogConfig.Level", Kind: modelcheck.KindEnum, Enum: []string{"OFF", "ERROR", "INFO", "TRACE"}},
		{Path: "Name", Kind: modelcheck.KindLength, Min: 1, Max: 256},
		{Path: "Name", Kind: modelcheck.KindPattern, Pat: regexp.MustCompile(`^[/\.\-_A-Za-z0-9]+$`)},
	},
}
